// webapp/src/app/core/header/request-feature/request-feature.component.ts
import { booleanAttribute, Component, input } from '@angular/core';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { BrnTooltipContentDirective } from '@spartan-ng/ui-tooltip-brain';
import { HlmTooltipComponent, HlmTooltipTriggerDirective } from '@spartan-ng/ui-tooltip-helm';
import { LucideAngularModule, Sparkles } from 'lucide-angular';

@Component({
  selector: 'app-request-feature',
  standalone: true,
  imports: [LucideAngularModule, HlmButtonModule, HlmTooltipComponent, HlmTooltipTriggerDirective, BrnTooltipContentDirective],
  templateUrl: './request-feature.component.html'
})
export class RequestFeatureComponent {
  protected Sparkles = Sparkles;

  iconOnly = input(false, { transform: booleanAttribute });
}

<hlm-tooltip>
  <a
    hlmBtn
    hlmTooltipTrigger
    hlmTooltipContentClass="bg-purple-100 dark:bg-purple-800 dark:border-purple-500 border-purple-300 text-github-upsell-foreground dark:text-popover-foreground"
    aria-describedby="Request a feature"
    data-canny-link
    href="https://hephaestus.canny.io/feature-requests"
    class="border-github-upsell-foreground text-github-upsell-foreground hover:text-github-upsell-foreground hover:bg-purple-500/10 dark:hover:bg-purple-500/20 flex gap-2"
    variant="outline"
    [size]="iconOnly() ? 'icon' : 'default'"
  >
    <lucide-angular [img]="Sparkles" class="size-4" />
    @if (!iconOnly()) {
      Request&nbsp;a&nbsp;feature
    }
  </a>
  @if (iconOnly()) {
    <span *brnTooltipContent class="flex items-center">Request&nbsp;a&nbsp;feature</span>
  }
</hlm-tooltip>

// webapp-react/src/components/core/RequestFeature.tsx
import { Button } from "@/components/ui/button";
import {
	Tooltip,
	TooltipContent,
	TooltipTrigger,
} from "@/components/ui/tooltip";
import { Sparkles } from "lucide-react";

interface RequestFeatureProps {
	/** Whether to show only the icon without text */
	iconOnly?: boolean;
}

export default function RequestFeature({
	iconOnly = false,
}: RequestFeatureProps) {
	return (
		<Tooltip>
			<TooltipTrigger asChild>
				<Button
					variant="outline"
					size={iconOnly ? "icon" : "default"}
					className="border-github-upsell-foreground dark:border-github-upsell-foreground text-github-upsell-foreground hover:text-github-upsell-foreground hover:bg-github-upsell-foreground/10 dark:hover:bg-github-upsell-foreground/10 flex gap-2"
					asChild
				>
					<a
						href="https://hephaestus.canny.io/feature-requests"
						data-canny-link
						aria-describedby="Request a feature"
					>
						<Sparkles />
						{!iconOnly && <span>Request&nbsp;a&nbsp;feature</span>}
					</a>
				</Button>
			</TooltipTrigger>
			{iconOnly && <TooltipContent>Request&nbsp;a&nbsp;feature</TooltipContent>}
		</Tooltip>
	);
}
