// webapp/src/app/mentor/messages/messages.component.ts
import { Component, inject, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, BotMessageSquare } from 'lucide-angular';
import { HlmAvatarModule } from '@spartan-ng/ui-avatar-helm';
import { SecurityStore } from '@app/core/security/security-store.service';
import { Message } from '@app/core/modules/openapi';
import { HlmSkeletonComponent } from '@spartan-ng/ui-skeleton-helm';
import { ChatSummaryComponent } from '../chat-summary/chat-summary.component';
import { PrsOverviewComponent } from '../prs-overview/prs-overview.component';
import { getSummary, getPullRequests } from './message-parser';

@Component({
  selector: 'app-messages',
  templateUrl: './messages.component.html',
  imports: [CommonModule, LucideAngularModule, HlmAvatarModule, HlmSkeletonComponent, ChatSummaryComponent, PrsOverviewComponent]
})
export class MessagesComponent {
  protected BotMessageSquare = BotMessageSquare;
  protected Message = Message;

  securityStore = inject(SecurityStore);
  messages = input<(Message | Summary)[]>([]);
  isLoading = input<boolean>(false);

  getSummary = getSummary;
  getPullRequests = getPullRequests;
}

<div class="flex flex-col gap-4">
  @if (isLoading()) {
    @for (i of [1, 2, 3, 4]; track i) {
      <div class="flex w-full" [ngClass]="{ 'justify-end': i % 2 === 0 }">
        @if (i % 2 === 0) {
          <div>
            <hlm-skeleton class="rounded-lg inline-block w-64 h-12" />
            <div class="flex justify-end">
              <hlm-skeleton class="h-4 w-32 justify-end" />
            </div>
          </div>
        } @else {
          <hlm-skeleton class="w-10 h-10 rounded-full" />
          <div class="ml-3">
            <hlm-skeleton class="rounded-lg inline-block w-64 h-12" />
            <hlm-skeleton class="h-4 w-32" />
          </div>
        }
      </div>
    }
  } @else {
    @for (message of messages(); track message.id) {
      <div
        class="flex w-full"
        [ngClass]="{
          'justify-end': message.sender === Message.SenderEnum.User,
          'justify-start': message.sender === Message.SenderEnum.Mentor
        }"
      >
        <div
          class="flex space-x-2"
          [ngClass]="{
            'flex-row-reverse': message.sender === Message.SenderEnum.User,
            'md:max-w-[60%]': getSummary(message) == null
          }"
        >
          @if (message.sender === Message.SenderEnum.Mentor) {
            <div class="mr-2 flex flex-col">
              <div class="w-10 h-10 bg-transparent border-2 border-cyan-500 rounded-full flex items-center justify-center">
                <ng-icon name="lucideBotMessageSquare" class="text-2xl text-cyan-500" />
              </div>
            </div>
          }
          <div
            class="flex flex-col space-y-2"
            [ngClass]="{
              'items-end': message.sender === Message.SenderEnum.User,
              'items-start': message.sender === Message.SenderEnum.Mentor
            }"
          >
            @if (getSummary(message) !== null) {
              <app-chat-summary
                [status]="getSummary(message)?.status || []"
                [impediments]="getSummary(message)?.impediments || []"
                [promises]="getSummary(message)?.promises || []"
              />
            }
            <div
              [ngClass]="{
                'bg-cyan-500 dark:bg-cyan-600 text-white': message.sender === Message.SenderEnum.User,
                'bg-muted text-primary': message.sender === Message.SenderEnum.Mentor,
                'md:max-w-[60%]': getSummary(message) !== null
              }"
              class="p-3 px-4 rounded-lg inline-block w-fit"
            >
              @if (getSummary(message) !== null) {
                <p>{{ getSummary(message)?.response }}</p>
              } @else {
                @if (getPullRequests(message) !== null) {
                  <p>{{ getPullRequests(message)?.response }}</p>
                } @else {
                  <p>{{ message.content }}</p>
                }
              }
            </div>
            @if (getPullRequests(message) !== null) {
              <app-prs-overview [pullRequests]="getPullRequests(message)?.development || []"></app-prs-overview>
            }
            <span class="text-xs text-muted-foreground"> {{ message.sender === Message.SenderEnum.User ? 'You' : 'AI Mentor' }} · {{ message.sentAt | date: 'shortTime' }} </span>
          </div>
        </div>
      </div>
    }
  }
</div>

// webapp-react/src/components/old/chat/Messages.tsx
import { format } from 'date-fns';
import { BotIcon } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { cn } from "@/lib/utils";
import { getSummary, getPullRequests } from './message-parser';
import { ChatSummary } from './ChatSummary';
import { PullRequestsOverview } from './PullRequestsOverview';
import type { Message } from './types';
import { MessageSender } from './types';

interface MessagesProps {
  messages: Message[];
  isLoading?: boolean;
  className?: string;
}

export function Messages({ messages = [], isLoading = false, className }: MessagesProps) {
  return (
    <div className={cn("flex flex-col gap-4", className)}>
      {isLoading ? (
        // Loading skeleton UI
        Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className={`flex w-full ${i % 2 === 0 ? 'justify-end' : ''}`}>
            {i % 2 === 0 ? (
              <div>
                <Skeleton className="rounded-lg inline-block w-64 h-12" />
                <div className="flex justify-end">
                  <Skeleton className="h-4 w-32 justify-end" />
                </div>
              </div>
            ) : (
              <>
                <Skeleton className="w-10 h-10 rounded-full" />
                <div className="ml-3">
                  <Skeleton className="rounded-lg inline-block w-64 h-12" />
                  <Skeleton className="h-4 w-32" />
                </div>
              </>
            )}
          </div>
        ))
      ) : (
        // Actual messages list
        messages.map((message) => {
          const summary = getSummary(message);
          const pullRequests = getPullRequests(message);
          const isUser = message.sender === MessageSender.User;

          return (
            <div 
              key={message.id} 
              className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'}`}
            >
              <div 
                className={`flex space-x-2 ${isUser ? 'flex-row-reverse' : ''} ${
                  summary == null ? 'md:max-w-[60%]' : ''
                }`}
              >
                {message.sender === MessageSender.Mentor && (
                  <div className="mr-2 flex flex-col">
                    <div className="w-10 h-10 bg-transparent border-2 border-cyan-500 rounded-full flex items-center justify-center">
                      <BotIcon className="text-2xl text-cyan-500" />
                    </div>
                  </div>
                )}
                <div 
                  className={`flex flex-col space-y-2 ${
                    isUser ? 'items-end' : 'items-start'
                  }`}
                >
                  {summary !== null && (
                    <ChatSummary 
                      status={summary.status || []} 
                      impediments={summary.impediments || []} 
                      promises={summary.promises || []} 
                    />
                  )}
                  <div
                    className={cn(
                      "p-3 px-4 rounded-lg inline-block w-fit",
                      isUser ? "bg-cyan-500 dark:bg-cyan-600 text-white" : "bg-muted text-primary",
                      summary !== null ? "md:max-w-[60%]" : ""
                    )}
                  >
                    {summary !== null ? (
                      <p>{summary.response}</p>
                    ) : pullRequests !== null ? (
                      <p>{pullRequests.response}</p>
                    ) : (
                      <p>{message.content}</p>
                    )}
                  </div>
                  {pullRequests !== null && (
                    <PullRequestsOverview 
                      pullRequests={pullRequests.development || []} 
                    />
                  )}
                  <span className="text-xs text-muted-foreground">
                    {isUser ? 'You' : 'AI Mentor'} · {format(new Date(message.sentAt), 'p')}
                  </span>
                </div>
              </div>
            </div>
          );
        })
      )}
    </div>
  );
}
