// webapp/src/components/ui/label.tsx
"use client";

import type * as React from "react";

import { cn } from "@/lib/utils";

function Label({ className, ...props }: React.ComponentProps<"label">) {
	return (
		<label
			data-slot="label"
			className={cn(
				"gap-2 text-sm leading-none font-medium group-data-[disabled=true]:opacity-50 peer-disabled:opacity-50 flex items-center select-none group-data-[disabled=true]:pointer-events-none peer-disabled:cursor-not-allowed",
				className,
			)}
			{...props}
		/>
	);
}

export { Label };

// webapp/src/app/ui/label/label.component.ts
import { Component, computed, input } from '@angular/core';
import type { ClassValue } from 'clsx';
import { cn } from 'app/utils';
import { cva } from 'app/storybook.helper';

const [labelVariants, args, argTypes] = cva('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70');

export { args, argTypes };

@Component({
  selector: 'app-label',
  standalone: true,
  templateUrl: './label.component.html'
})
export class LabelComponent {
  class = input<ClassValue>('');
  for = input<string>('');

  computedClass = computed(() => cn(labelVariants({}), this.class()));
}

<label
  [class]="computedClass()"
  [for]="for()"
>
  <ng-content/>
</label>
