// webapp-react/src/components/practices/BadPracticeLegendCard.tsx
import { stateConfig } from "./utils";
import { Card, CardContent } from "@/components/ui/card";

export function BadPracticeLegendCard() {
  const stateList = Object.values(stateConfig);

  return (
    <Card>
      <CardContent className="flex flex-col gap-y-4 py-4">
        <div className="flex flex-col gap-2 sm:min-w-[250px]">
          <h4 className="mb-2 text-lg font-semibold leading-none tracking-tight">Icons</h4>
          {stateList.map((state) => {
            const Icon = state.icon;
            return (
              <div key={state.text} className="flex flex-row items-center text-center gap-2">
                <Icon className={`${state.color} size-5`} />
                <span className="text-github-muted-foreground">{state.text}</span>
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}

// webapp/src/app/user/bad-practice-legend-card/bad-practice-legend-card.component.ts
import { Component, computed } from '@angular/core';
import { stateConfig } from '@app/utils';
import { HlmCardImports } from '@spartan-ng/ui-card-helm';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideRocket, lucideCheck, lucideFlame, lucideTriangleAlert, lucideOctagonX, lucideBan, lucideCircleHelp, lucideBug } from '@ng-icons/lucide';

@Component({
  selector: 'app-bad-practice-legend-card',
  imports: [HlmCardImports, NgIcon],
  templateUrl: './bad-practice-legend-card.component.html',
  providers: [provideIcons({ lucideRocket, lucideCheck, lucideFlame, lucideTriangleAlert, lucideBug, lucideOctagonX, lucideBan, lucideCircleHelp })]
})
export class BadPracticeLegendCardComponent {
  stateList = computed(() => {
    return Object.values(stateConfig);
  });
}

<div hlmCard>
  <div hlmCardContent class="flex flex-col gap-y-4 py-4">
    <div class="flex flex-col gap-2 sm:min-w-[250px]">
      <h4 class="mb-2 text-lg font-semibold leading-none tracking-tight">Icons</h4>
      @for (state of stateList(); track state.text) {
        <div class="flex flex-row items-center text-center gap-2">
          <ng-icon [name]="state.icon" class="{{ state.color }}" size="20"></ng-icon>
          <span class="text-github-muted-foreground">{{ state.text }}</span>
        </div>
      }
    </div>
  </div>
</div>
