// webapp-react/src/features/mentor/AIMentor.tsx
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Link } from "@tanstack/react-router";
import { BotMessageSquare } from "lucide-react";

interface AIMentorProps {
  /** Whether to show only the icon without text */
  iconOnly?: boolean;
}

export default function AIMentor({ iconOnly = false }: AIMentorProps) {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            variant="outline"
            size={iconOnly ? "icon" : "default"}
            className="border-cyan-500 dark:border-cyan-500 text-cyan-500 hover:text-cyan-500 hover:bg-cyan-500/10 dark:hover:bg-cyan-500/10 flex gap-2"
            asChild
          >
            <Link
              to="/mentor"
              aria-describedby="AI Mentor"
            >
              <BotMessageSquare className="h-4 w-4" />
              {!iconOnly && <span>AI&nbsp;Mentor</span>}
            </Link>
          </Button>
        </TooltipTrigger>
        {iconOnly && (
          <TooltipContent className="bg-cyan-50 dark:bg-cyan-800 dark:border-cyan-500 border-cyan-300 text-cyan-500 dark:text-cyan-200">
            <span className="flex items-center">AI&nbsp;Mentor</span>
          </TooltipContent>
        )}
      </Tooltip>
    </TooltipProvider>
  );
}

// webapp/src/app/core/header/ai-mentor/ai-mentor.component.ts
import { booleanAttribute, Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { BrnTooltipContentDirective } from '@spartan-ng/ui-tooltip-brain';
import { HlmTooltipComponent, HlmTooltipTriggerDirective } from '@spartan-ng/ui-tooltip-helm';
import { LucideAngularModule, BotMessageSquare } from 'lucide-angular';

@Component({
  selector: 'app-ai-mentor',
  imports: [LucideAngularModule, HlmButtonModule, HlmTooltipComponent, HlmTooltipTriggerDirective, BrnTooltipContentDirective, RouterModule],
  templateUrl: './ai-mentor.component.html'
})
export class AiMentorComponent {
  protected BotMessageSquare = BotMessageSquare;

  iconOnly = input(false, { transform: booleanAttribute });
}

<hlm-tooltip>
    <a
      hlmBtn
      hlmTooltipTrigger
      hlmTooltipContentClass="bg-purple-100 dark:bg-purple-800 dark:border-purple-500 border-purple-300 text-github-upsell-foreground dark:text-popover-foreground"
      aria-describedby="AI Mentor"
      class="border-cyan-500 cursor-pointer text-cyan-500 hover:text-cyan-500  hover:bg-cyan-500/10 dark:hover:bg-cyan-500/20 gap-2"
      variant="outline"
      [size]="iconOnly() ? 'icon' : 'default'"
      [routerLink]="[ '/', 'chat' ]" 
      routerLinkActive="active"
    >
      <lucide-angular [img]="BotMessageSquare" class="size-4" />
      @if (!iconOnly()) {
        AI&nbsp;Mentor
      }
    </a>
    @if (iconOnly()) {
      <span *brnTooltipContent class="flex items-center">AI&nbsp;Mentor</span>
    }
  </hlm-tooltip>
