// webapp/src/app/about/about.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { lastValueFrom } from 'rxjs';
import { HlmAvatarModule } from '@spartan-ng/ui-avatar-helm';
import { RepositoryService } from '@app/core/modules/openapi';

@Component({
  selector: 'app-about',
  imports: [HlmAvatarModule],
  templateUrl: './about.component.html'
})
export class AboutComponent {
  http = inject(HttpClient);
  repositoryService = inject(RepositoryService);

  query = injectQuery(() => ({
    queryKey: ['contributors'],
    queryFn: async () => lastValueFrom(this.repositoryService.getContributorsByRepositoryName('ls1intum', 'Hephaestus')),
    gcTime: Infinity
  }));

  projectManager = computed(() => {
    const data = this.query.data();
    if (!data) {
      return undefined;
    }
    // 5898705 is the id of the project manager Felix T.J. Dietrich
    return data.find((contributor) => contributor.id === 5898705);
  });

  contributors = computed(() => {
    const data = this.query.data();
    if (!data) {
      return undefined;
    }
    return data.filter((contributor) => contributor.user.id !== 5898705 && !contributor.user.login.includes('[bot]'));
  });
}

<div class="flex flex-col gap-4">
  <h1 class="text-3xl font-bold">About</h1>
  <p class="mb-4">
    Hephaestus is built to help software teams work better together. Our tools — like code review leaderboards and AI-guided reflection sessions — support agile practices and
    continuous improvement.
  </p>
  <h2 class="text-2xl font-semibold">Team</h2>
  @if (query.isPending()) {
    <span class="text-muted-foreground">Loading...</span>
  } @else if (query.error()) {
    <span class="text-destructive">An error has occurred</span>
  }

  @if (projectManager(); as projectManager) {
    <div class="flex items-center gap-3 mb-4">
      <a
        [href]="projectManager.user.htmlUrl"
        target="_blank"
        rel="noopener noreferrer"
        class="hover:scale-105 transition-all hover:shadow-secondary-foreground/15 hover:shadow-lg rounded-full"
      >
        <hlm-avatar class="size-32">
          <img [src]="projectManager.user.avatarUrl" [alt]="projectManager.user.login + '\'s avatar'" hlmAvatarImage />
          <span hlmAvatarFallback>{{ projectManager.user.login.slice(0, 2).toUpperCase() }}</span>
        </hlm-avatar>
      </a>
      <div>
        <div class="text-2xl font-semibold">Felix T.J. Dietrich</div>
        <div class="text-lg text-muted-foreground">Project Manager</div>
        <a href="https://ase.cit.tum.de/people/dietrich/" target="_blank" rel="noopener noreferrer" class="text-primary underline-offset-4 hover:underline">Website</a>
      </div>
    </div>
  }

  @if (contributors(); as contributors) {
    <h3 class="text-lg font-bold">Contributors</h3>
    <div class="flex flex-wrap gap-2">
      @for (contributor of contributors; track contributor.id) {
        <a
          [href]="contributor.user.htmlUrl"
          target="_blank"
          rel="noopener noreferrer"
          class="hover:scale-105 transition-all hover:shadow-secondary-foreground/15 hover:shadow-lg rounded-full"
        >
          <hlm-avatar class="size-20">
            <img [src]="contributor.user.avatarUrl" [alt]="contributor.user.login + '\'s avatar'" hlmAvatarImage />
            <span hlmAvatarFallback>{{ contributor.user.login.slice(0, 2).toUpperCase() }}</span>
          </hlm-avatar>
        </a>
      }
    </div>
  }
</div>

// webapp-react/src/routes/about.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/about")({
  component: About,
});

function About() {
  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-3xl font-bold">About</h1>
      <p className="mb-4">
        Hephaestus is built to help software teams work better together. Our tools — like code review leaderboards and AI-guided reflection sessions — support agile practices and
        continuous improvement.
      </p>
      <h2 className="text-2xl font-semibold">Team</h2>
      <div className="flex items-center gap-3 mb-4">
        <div className="size-32 rounded-full overflow-hidden">
          <img src="/images/felix_dietrich.jpg" alt="Felix T.J. Dietrich" />
        </div>
        <div>
          <div className="text-2xl font-semibold">Felix T.J. Dietrich</div>
          <div className="text-lg text-muted-foreground">Project Manager</div>
          <a href="https://ase.cit.tum.de/people/dietrich/" target="_blank" rel="noopener noreferrer" className="text-primary underline-offset-4 hover:underline">Website</a>
        </div>
      </div>
      <h3 className="text-lg font-bold">Contributors</h3>
      <div className="flex flex-wrap gap-2">
        {/* Placeholder for contributors - would be dynamically loaded in a real implementation */}
      </div>
    </div>
  );
}
