// webapp-react/src/components/issues/IssueCard.tsx
import dayjs from 'dayjs';
import { Circle as CircleIcon, CheckCircle as CheckCircleIcon } from 'lucide-react';
import { Card, CardFooter } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { GithubLabel } from '../github/GithubLabel';
import { cn } from '@/lib/utils';

type PrState = 'OPEN' | 'CLOSED';

export interface IssueCardProps {
  isLoading?: boolean;
  className?: string;
  title?: string;
  number?: number;
  additions?: number;
  deletions?: number;
  htmlUrl?: string;
  repositoryName?: string;
  createdAt?: string;
  state?: PrState;
  isDraft?: boolean;
  isMerged?: boolean;
  pullRequestLabels?: Array<{
    name: string;
    color: string;
    description?: string;
  }>;
}

export function IssueCard({
  isLoading = false,
  className = '',
  title = '',
  number,
  additions = 0,
  deletions = 0,
  htmlUrl = '#',
  repositoryName = '',
  createdAt = '',
  state = 'OPEN',
  // Remove unused parameters
  pullRequestLabels = []
}: IssueCardProps) {
  const displayCreated = createdAt ? dayjs(createdAt) : null;
  // Replace code blocks with styled text
  const displayTitle = title.replace(/`([^`]+)`/g, '<code class="textCode">$1</code>');

  const getIssueIconAndColor = () => {
    switch (state) {
      case 'OPEN':
        return { icon: <CircleIcon className="w-4 h-4 text-green-500" /> };
      case 'CLOSED':
        return { icon: <CheckCircleIcon className="w-4 h-4 text-purple-500" /> };
      default:
        return { icon: <CircleIcon className="w-4 h-4 text-muted-foreground" /> };
    }
  };
  
  const { icon } = getIssueIconAndColor();

  return (
    <a 
      href={htmlUrl} 
      target="_blank" 
      rel="noopener noreferrer"
    >
      <Card 
        className={cn(
          "flex flex-col gap-1 pt-6 w-72", 
          !isLoading && "hover:bg-accent/50 cursor-pointer", 
          className
        )}
      >
        <div className="flex flex-col gap-1 px-6">
          <div className="flex justify-between items-center text-sm text-github-muted-foreground">
            <span className="font-medium flex justify-center items-center space-x-1">
              {isLoading ? (
                <>
                  <Skeleton className="size-5 bg-green-500/30" />
                  <Skeleton className="h-4 w-16 lg:w-36" />
                </>
              ) : (
                <>
                  <span className="mr-1">{icon}</span>
                  <span>{repositoryName} #{number} on {displayCreated?.format('MMM D')}</span>
                </>
              )}
            </span>
            <span className="flex items-center space-x-2">
              {isLoading ? (
                <>
                  <Skeleton className="h-4 w-8 bg-green-500/30" />
                  <Skeleton className="h-4 w-8 bg-destructive/20" />
                </>
              ) : (
                <>
                  <span className="text-github-success-foreground font-bold">+{additions}</span>
                  <span className="text-github-danger-foreground font-bold">-{deletions}</span>
                </>
              )}
            </span>
          </div>

          <span className="flex justify-between font-medium contain-inline-size">
            {isLoading ? (
              <Skeleton className="h-6 w-3/4 mb-6" />
            ) : (
              <div dangerouslySetInnerHTML={{ __html: displayTitle }} />
            )}
          </span>
        </div>
        
        {!isLoading && pullRequestLabels.length > 0 && (
          <CardFooter className="flex flex-wrap gap-2 px-6 pb-6 space-x-0">
            {pullRequestLabels.map(label => (
              <GithubLabel key={label.name} label={label} />
            ))}
          </CardFooter>
        )}
      </Card>
    </a>
  );
}

// webapp/src/app/user/issue-card/issue-card.component.ts
import { Component, computed, input } from '@angular/core';
import { PullRequestInfo, LabelInfo } from '@app/core/modules/openapi';
import { NgIcon } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed, octGitPullRequestDraft, octGitMerge, octX } from '@ng-icons/octicons';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmSkeletonComponent } from '@spartan-ng/ui-skeleton-helm';
import { GithubLabelComponent } from '@app/ui/github-label/github-label.component';
import dayjs from 'dayjs';
import { cn } from '@app/utils';

@Component({
  selector: 'app-issue-card',
  templateUrl: './issue-card.component.html',
  imports: [NgIcon, HlmCardModule, HlmSkeletonComponent, GithubLabelComponent]
})
export class IssueCardComponent {
  protected readonly octCheck = octCheck;
  protected readonly octX = octX;
  protected readonly octComment = octComment;
  protected readonly octFileDiff = octFileDiff;

  isLoading = input(false);
  class = input('');
  title = input<string>();
  number = input<number>();
  additions = input<number>();
  deletions = input<number>();
  htmlUrl = input<string>();
  repositoryName = input<string>();
  createdAt = input<string>();
  state = input<PullRequestInfo.StateEnum>();
  isDraft = input<boolean>();
  isMerged = input<boolean>();
  pullRequestLabels = input<Array<LabelInfo>>();

  displayCreated = computed(() => dayjs(this.createdAt()));
  displayTitle = computed(() => (this.title() ?? '').replace(/`([^`]+)`/g, '<code class="textCode">$1</code>'));
  computedClass = computed(() => cn('w-72', !this.isLoading() ? 'hover:bg-accent/50 cursor-pointer' : '', this.class()));

  issueIconAndColor = computed(() => {
    var icon: string;
    var color: string;

    if (this.state() === PullRequestInfo.StateEnum.Open) {
      if (this.isDraft()) {
        icon = octGitPullRequestDraft;
        color = 'text-github-muted-foreground';
      } else {
        icon = octGitPullRequest;
        color = 'text-github-open-foreground';
      }
    } else {
      if (this.isMerged()) {
        icon = octGitMerge;
        color = 'text-github-done-foreground';
      } else {
        icon = octGitPullRequestClosed;
        color = 'text-github-closed-foreground';
      }
    }

    return { icon, color };
  });
}

<a hlmCard variant="profile" [class]="computedClass()" [href]="url()" target="_blank" rel="noopener noreferrer">
  <div hlmCardContent variant="profile">
    <div class="flex justify-between items-center text-sm text-github-muted-foreground">
      <span class="font-medium flex justify-center items-center space-x-1">
        @if (isLoading()) {
          <hlm-skeleton class="size-5 bg-green-500/30"></hlm-skeleton>
          <hlm-skeleton class="h-4 w-16 lg:w-36"></hlm-skeleton>
        } @else {
          @if (state() === 'OPEN') {
            <ng-icon [svg]="octGitPullRequest" size="18" class="mr-1 text-github-success-foreground"></ng-icon>
          } @else {
            <ng-icon [svg]="octGitPullRequestClosed" size="18" class="mr-1 text-github-danger-foreground"></ng-icon>
          }

          {{ repositoryName() }} #{{ number() }} on {{ displayCreated().format('MMM D') }}
        }
      </span>
      <span class="flex items-center space-x-2">
        @if (isLoading()) {
          <hlm-skeleton class="h-4 w-8 bg-green-500/30"></hlm-skeleton>
          <hlm-skeleton class="h-4 w-8 bg-destructive/20"></hlm-skeleton>
        } @else {
          <span class="text-github-success-foreground font-bold">+{{ additions() }}</span>
          <span class="text-github-danger-foreground font-bold">-{{ deletions() }}</span>
        }
      </span>
    </div>

    <span class="containerSize flex justify-between font-medium mb-3">
      @if (isLoading()) {
        <hlm-skeleton class="h-6 w-3/4"></hlm-skeleton>
      } @else {
        <div [innerHTML]="displayTitle()" class="truncate"></div>
      }
    </span>
  </div>
  @if (!isLoading()) {
    <div hlmCardFooter class="flex flex-wrap gap-2 p-0 space-x-0">
      @for (label of pullRequestLabels(); track label.name) {
        @let labelColors = hexToRgb(label.color ?? 'FFFFFF');
        <span
          class="px-2 py-0.5 rounded-[2rem] text-xs font-medium dark:border gh-label"
          [style.--label-r]="labelColors.r"
          [style.--label-g]="labelColors.g"
          [style.--label-b]="labelColors.b"
          [style.--label-h]="labelColors.h"
          [style.--label-s]="labelColors.s"
          [style.--label-l]="labelColors.l"
        >
          {{ label.name }}
        </span>
      }
    </div>
  }
</a>
