// webapp/src/components/leaderboard/LeaderboardOverview.tsx
import {
	differenceInHours,
	differenceInMinutes,
	differenceInSeconds,
	isPast,
} from "date-fns";
import {
	CalendarClock,
	MoveRight,
	TrendingDown,
	TrendingUp,
} from "lucide-react";
import { useEffect, useState } from "react";
import type { LeaderboardEntry } from "@/api/types.gen";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { LeagueInfoDialog } from "./LeagueInfoDialog";
import { LeagueProgressCard } from "./LeagueProgressCard";

export interface LeaderboardOverviewProps {
	leaderboardEntry: LeaderboardEntry;
	leaguePoints: number;
	leaderboardEnd?: string;
	leaguePointsChange?: number;
}

export function LeaderboardOverview({
	leaderboardEntry,
	leaguePoints,
	leaderboardEnd,
	leaguePointsChange = 0,
}: LeaderboardOverviewProps) {
	const [leagueInfoOpen, setLeagueInfoOpen] = useState(false);
	const [countdown, setCountdown] = useState<string>("Calculating...");
	const user = leaderboardEntry.user;

	// Use an effect to update the countdown timer every second
	useEffect(() => {
		// Calculate countdown function that uses the current leaderboardEnd
		const calculateCountdown = () => {
			if (!leaderboardEnd) return "N/A";

			const endDate = new Date(leaderboardEnd);

			if (isPast(endDate)) {
				return "Ended";
			}

			const now = new Date();
			const diffHours = differenceInHours(endDate, now);
			const diffMinutes = differenceInMinutes(endDate, now) % 60;
			const diffSeconds = differenceInSeconds(endDate, now) % 60;

			if (diffHours > 24) {
				const days = Math.floor(diffHours / 24);
				const hours = diffHours % 24;
				return `${days}d ${hours}h`;
			}

			if (diffHours > 0) {
				return `${diffHours}h ${diffMinutes}m`;
			}

			if (diffMinutes > 0) {
				return `${diffMinutes}m ${diffSeconds}s`;
			}

			return `${diffSeconds}s`;
		};

		// Initial calculation
		setCountdown(calculateCountdown());

		// Update the countdown every second
		const timer = setInterval(() => {
			setCountdown(calculateCountdown());
		}, 1000);

		// Cleanup interval on unmount
		return () => clearInterval(timer);
	}, [leaderboardEnd]);

	if (!user) {
		return null;
	}

	// Scroll to the user's rank in the leaderboard table
	const scrollToRank = (rank: number) => {
		const element = document.getElementById(`rank-${rank}`);
		if (element) {
			element.scrollIntoView({ behavior: "smooth" });
		}
	};

	return (
		<Card>
			<CardContent>
				<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 items-center justify-between gap-4">
					<Button
						variant="ghost"
						className="h-full sm:col-span-2 md:col-span-1 flex flex-col items-center"
						onClick={() => scrollToRank(leaderboardEntry.rank)}
					>
						<div className="flex flex-col items-center gap-2">
							<div className="flex items-end gap-2">
								<span>
									<span className="text-3xl font-light text-muted-foreground">
										#
									</span>
									<span className="text-4xl text-primary font-light">
										{leaderboardEntry.rank}
									</span>
								</span>
								<div className="h-10 w-10 rounded-full bg-muted flex items-center justify-center overflow-hidden">
									{user.avatarUrl ? (
										<img
											src={user.avatarUrl}
											alt={`${user.name}'s avatar`}
											className="h-full w-full object-cover"
										/>
									) : (
										<span className="text-sm font-medium">
											{user.name.slice(0, 2).toUpperCase()}
										</span>
									)}
								</div>
							</div>
							<span className="text-muted-foreground">{user.name}</span>
						</div>
					</Button>

					<div className="flex flex-col items-center gap-1 text-center">
						<div className="flex items-center gap-1">
							<CalendarClock className="h-4 w-4 text-muted-foreground" />
							<span className="text-sm text-muted-foreground">
								Leaderboard ends in:
							</span>
						</div>
						<span className="text-xl font-medium">{countdown}</span>
						<div className="flex flex-wrap items-center justify-center gap-1 mt-1 text-sm">
							<span className="text-muted-foreground">
								League points change:
							</span>
							<div className="flex items-center gap-1">
								<span className="font-medium">{leaguePointsChange}</span>
								{leaguePointsChange > 0 ? (
									<TrendingUp className="h-4 w-4" />
								) : leaguePointsChange < 0 ? (
									<TrendingDown className="h-4 w-4" />
								) : (
									<MoveRight className="h-4 w-4" />
								)}
							</div>
						</div>
					</div>

					<div className="flex flex-col items-center gap-1 text-center">
						<LeagueProgressCard
							leaguePoints={leaguePoints}
							onInfoClick={() => setLeagueInfoOpen(true)}
						/>
					</div>
				</div>
			</CardContent>

			<LeagueInfoDialog
				open={leagueInfoOpen}
				onOpenChange={setLeagueInfoOpen}
			/>
		</Card>
	);
}

// webapp/src/app/home/leaderboard/leaderboard-overview/leaderboard-overview.component.ts
import { Component, computed, inject, input, signal } from '@angular/core';
import { LeaderboardEntry, LeaderboardService } from '@app/core/modules/openapi';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { LeagueEloCardComponent } from '@app/ui/league/elo-card/elo-card.component';
import { HlmAvatarModule } from '@spartan-ng/ui-avatar-helm';
import { NgIconComponent } from '@ng-icons/core';
import { provideIcons } from '@ng-icons/core';
import { lucideClock, lucideTrendingUp, lucideTrendingDown, lucideMoveRight } from '@ng-icons/lucide';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { lastValueFrom } from 'rxjs';
import { ActivatedRoute } from '@angular/router';
import dayjs, { Dayjs } from 'dayjs/esm';

@Component({
  selector: 'app-leaderboard-overview',
  imports: [HlmCardModule, HlmButtonModule, HlmAvatarModule, LeagueEloCardComponent, NgIconComponent],
  templateUrl: './leaderboard-overview.component.html',
  providers: [provideIcons({ lucideClock, lucideTrendingUp, lucideTrendingDown, lucideMoveRight })]
})
export class LeaderboardOverviewComponent {
  private readonly route = inject(ActivatedRoute);
  leaderboardEntry = input.required<LeaderboardEntry>();
  leaguePoints = input.required<number>();
  leaderboardService = inject(LeaderboardService);

  leaderboardEnd = signal<Dayjs>(dayjs());
  leaderboardTimeUntilEnd = computed(() => {
    const diff = this.leaderboardEnd().diff(dayjs(), 'hours');
    if (diff < 0) {
      return 'Ended';
    }
    if (diff > 24) {
      return `${Math.floor(diff / 24)}d ${diff % 24}h`;
    }
    return `${diff}h`;
  });

  leagueChangeQuery = injectQuery(() => ({
    queryKey: ['league', 'change', this.leaderboardEntry().user.login],
    queryFn: async () => lastValueFrom(this.leaderboardService.getUserLeagueStats(this.leaderboardEntry().user.login, this.leaderboardEntry())),
    select: (data) => data.leaguePointsChange
  }));

  constructor() {
    this.route.queryParams.subscribe((params) => {
      if (params['before']) {
        this.leaderboardEnd.set(dayjs(params['before']));
      }
    });
  }

  scrollToRank(rank: number) {
    const element = document.getElementById(`rank-${rank}`);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

<div hlmCard>
  <div hlmCardContent class="py-4">
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 items-center justify-between gap-4">
      <button hlmBtn variant="ghost" class="h-full sm:col-span-2 md:col-span-1" (click)="scrollToRank(leaderboardEntry().rank)">
        <div class="flex flex-col items-center gap-2">
          <div class="flex items-end gap-2">
            <span>
              <span class="text-3xl font-light text-muted-foreground">#</span>
              <span class="text-4xl text-primary font-light">{{ leaderboardEntry().rank }}</span>
            </span>
            <hlm-avatar>
              <img [src]="leaderboardEntry().user.avatarUrl" [alt]="leaderboardEntry().user.name + '\'s avatar'" hlmAvatarImage />
              <span hlmAvatarFallback>
                {{ leaderboardEntry().user.name.slice(0, 2).toUpperCase() }}
              </span>
            </hlm-avatar>
          </div>
          <span class="text-muted-foreground">{{ leaderboardEntry().user.name }}</span>
        </div>
      </button>

      <div class="flex flex-col items-center gap-1 text-center">
        <div class="flex items-center gap-1">
          <ng-icon name="lucideClock" class="text-muted-foreground" />
          <span class="text-sm text-muted-foreground">Leaderboard ends in:</span>
        </div>
        <span class="text-xl font-medium">{{ leaderboardTimeUntilEnd() }}</span>
        <div class="flex items-center gap-1 mt-1 text-sm">
          <span class="text-muted-foreground">League points change:</span>
          @if (leagueChangeQuery.isSuccess()) {
            @let change = leagueChangeQuery.data();
            <span class="font-medium">{{ change }}</span>
            @if (change > 0) {
              <ng-icon name="lucideTrendingUp" />
            } @else if (change < 0) {
              <ng-icon name="lucideTrendingDown" />
            } @else {
              <ng-icon name="lucideMoveRight" />
            }
          } @else {
            <span class="font-medium">0</span>
            <ng-icon name="lucideMoveRight" />
          }
        </div>
      </div>

      <div class="flex flex-col items-center gap-1 text-center">
        <app-league-elo-card [leaguePoints]="leaguePoints()" />
      </div>
    </div>
  </div>
</div>
