// webapp-react/src/components/issues/IssueCard.tsx
import dayjs from 'dayjs';
import { Circle as CircleIcon, CheckCircle as CheckCircleIcon } from 'lucide-react';
import { Card, CardFooter } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { GithubLabel } from '../github/GithubLabel';
import { cn } from '@/lib/utils';

type PrState = 'OPEN' | 'CLOSED';

export interface IssueCardProps {
  isLoading?: boolean;
  className?: string;
  title?: string;
  number?: number;
  additions?: number;
  deletions?: number;
  htmlUrl?: string;
  repositoryName?: string;
  createdAt?: string;
  state?: PrState;
  isDraft?: boolean;
  isMerged?: boolean;
  pullRequestLabels?: Array<{
    name: string;
    color: string;
    description?: string;
  }>;
}

export function IssueCard({
  isLoading = false,
  className = '',
  title = '',
  number,
  additions = 0,
  deletions = 0,
  htmlUrl = '#',
  repositoryName = '',
  createdAt = '',
  state = 'OPEN',
  // Remove unused parameters
  pullRequestLabels = []
}: IssueCardProps) {
  const displayCreated = createdAt ? dayjs(createdAt) : null;
  // Replace code blocks with styled text
  const displayTitle = title.replace(/`([^`]+)`/g, '<code class="textCode">$1</code>');

  const getIssueIconAndColor = () => {
    switch (state) {
      case 'OPEN':
        return { icon: <CircleIcon className="w-4 h-4 text-green-500" /> };
      case 'CLOSED':
        return { icon: <CheckCircleIcon className="w-4 h-4 text-purple-500" /> };
      default:
        return { icon: <CircleIcon className="w-4 h-4 text-muted-foreground" /> };
    }
  };
  
  const { icon } = getIssueIconAndColor();

  return (
    <a 
      href={htmlUrl} 
      target="_blank" 
      rel="noopener noreferrer"
    >
      <Card 
        className={cn(
          "flex flex-col gap-1 pt-6 w-72", 
          !isLoading && "hover:bg-accent/50 cursor-pointer", 
          className
        )}
      >
        <div className="flex flex-col gap-1 px-6">
          <div className="flex justify-between items-center text-sm text-github-muted-foreground">
            <span className="font-medium flex justify-center items-center space-x-1">
              {isLoading ? (
                <>
                  <Skeleton className="size-5 bg-green-500/30" />
                  <Skeleton className="h-4 w-16 lg:w-36" />
                </>
              ) : (
                <>
                  <span className="mr-1">{icon}</span>
                  <span>{repositoryName} #{number} on {displayCreated?.format('MMM D')}</span>
                </>
              )}
            </span>
            <span className="flex items-center space-x-2">
              {isLoading ? (
                <>
                  <Skeleton className="h-4 w-8 bg-green-500/30" />
                  <Skeleton className="h-4 w-8 bg-destructive/20" />
                </>
              ) : (
                <>
                  <span className="text-github-success-foreground font-bold">+{additions}</span>
                  <span className="text-github-danger-foreground font-bold">-{deletions}</span>
                </>
              )}
            </span>
          </div>

          <span className="flex justify-between font-medium contain-inline-size">
            {isLoading ? (
              <Skeleton className="h-6 w-3/4 mb-6" />
            ) : (
              <div dangerouslySetInnerHTML={{ __html: displayTitle }} />
            )}
          </span>
        </div>
        
        {!isLoading && pullRequestLabels.length > 0 && (
          <CardFooter className="flex flex-wrap gap-2 px-6 pb-6 space-x-0">
            {pullRequestLabels.map(label => (
              <GithubLabel key={label.name} label={label} />
            ))}
          </CardFooter>
        )}
      </Card>
    </a>
  );
}

// webapp/src/app/core/issue-card/issue-card.component.ts
import { Component, computed, input } from '@angular/core';
import { PullRequest, PullRequestLabel, PullRequestReview } from '@app/core/modules/openapi';
import { NgIcon } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed, octX } from '@ng-icons/octicons';
import dayjs from 'dayjs';
import { NgStyle } from '@angular/common';
import { cn } from '@app/utils';

@Component({
  selector: 'app-issue-card',
  templateUrl: './issue-card.component.html',
  imports: [NgIcon, NgStyle],
  standalone: true
})
export class IssueCardComponent {
  class = input('');
  title = input.required<string>();
  number = input.required<number>();
  additions = input.required<number>();
  deletions = input.required<number>();
  url = input.required<string>();
  repositoryName = input.required<string>();
  reviews = input<Array<PullRequestReview>>([]);
  createdAt = input.required<string>();
  state = input.required<PullRequest.StateEnum>();
  pullRequestLabels = input.required<Array<PullRequestLabel>>();
  protected readonly octCheck = octCheck;
  protected readonly octX = octX;
  protected readonly octComment = octComment;
  protected readonly octGitPullRequest = octGitPullRequest;
  protected readonly octFileDiff = octFileDiff;
  protected readonly octGitPullRequestClosed = octGitPullRequestClosed;

  displayCreated = computed(() => dayjs(this.createdAt()));

  getMostRecentReview() {
    return this.reviews().reduce((latest, review) => {
      return new Date(review.updatedAt || 0) > new Date(latest.updatedAt || 0) ? review : latest;
    });
  }

  computedClass = computed(() => cn('border border-border bg-card rounded-lg p-4 w-72', this.class()));
}

<div [class]="computedClass()">
  <div class="flex justify-between items-center mb-2 text-xs text-gray-500">
    <span class="font-bold flex justify-center items-center space-x-1">
      @if (state() === 'OPEN') {
        <ng-icon [svg]="octGitPullRequest" size="16" class="mr-1 text-github-success-foreground"></ng-icon>
      } @else {
        <ng-icon [svg]="octGitPullRequestClosed" size="16" class="mr-1 text-github-danger-foreground"></ng-icon>
      }

      {{ repositoryName() }} #{{ number() }} on {{ displayCreated().format('MMM D') }}
    </span>
    <span class="flex items-center space-x-2">
      <span class="text-github-success-foreground font-bold">+{{ additions() }}</span>
      <span class="text-github-danger-foreground font-bold">-{{ deletions() }}</span>
    </span>
  </div>

  <a class="flex justify-between font-bold text-sm mb-3 hover:text-github-accent-foreground" href="{{ url() }}" target="_blank" rel="noopener noreferrer">
    {{ title() }}
    @if (reviews().length > 0 && getMostRecentReview(); as review) {
      @if (review.state === 'APPROVED') {
        <ng-icon [svg]="octCheck" size="16" class="text-github-success-foreground"></ng-icon>
      } @else if (review.state === 'DISMISSED') {
        <ng-icon [svg]="octX" size="16" class="text-github-danger-foreground"></ng-icon>
      } @else if (review.state === 'COMMENTED') {
        <ng-icon [svg]="octComment" size="16" class="text-github-muted-foreground"></ng-icon>
      } @else {
        <ng-icon [svg]="octFileDiff" size="16" class="text-github-danger-foreground"></ng-icon>
      }
    }
  </a>
  <div class="flex gap-1 flex-wrap">
    @for (label of pullRequestLabels(); track label.name) {
      <span class="px-2 py-1 rounded-full text-xs mr-2 text-neutral-100/95" [style.background-color]="label.color">{{ label.name }}</span>
    }
  </div>
</div>
