// webapp-react/src/components/profile/ReviewActivityCard.tsx
import { FormattedTitle } from "@/components/shared/FormattedTitle";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import {
	Tooltip,
	TooltipContent,
	TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import {
	CheckIcon,
	CommentIcon,
	FileDiffIcon,
	GitPullRequestIcon,
} from "@primer/octicons-react";
import { formatDistanceToNow } from "date-fns";
import { AwardIcon } from "lucide-react";

// Define the styling for different review states
const REVIEW_STATE_STYLES: Record<
	string,
	{
		icon: React.ElementType;
		color: string;
		skeletonColor: string;
		tooltip: string;
	}
> = {
	APPROVED: {
		icon: CheckIcon,
		color: "text-github-success-foreground",
		skeletonColor: "bg-github-success-foreground/30",
		tooltip: "Approved",
	},
	CHANGES_REQUESTED: {
		icon: FileDiffIcon,
		color: "text-github-danger-foreground",
		skeletonColor: "bg-github-danger-foreground/30",
		tooltip: "Changes Requested",
	},
	COMMENTED: {
		icon: CommentIcon,
		color: "text-github-muted-foreground",
		skeletonColor: "bg-github-muted-foreground/30",
		tooltip: "Commented",
	},
	UNKNOWN: {
		icon: GitPullRequestIcon,
		color: "text-github-muted-foreground",
		skeletonColor: "bg-github-muted-foreground/30",
		tooltip: "Reviewed",
	},
};

export interface ReviewActivityCardProps {
	isLoading: boolean;
	state?: "COMMENTED" | "APPROVED" | "CHANGES_REQUESTED" | "UNKNOWN";
	submittedAt?: Date;
	htmlUrl?: string;
	pullRequest?: {
		id?: number;
		title?: string;
		number?: number;
		state?: string;
		isDraft?: boolean;
		isMerged?: boolean;
		htmlUrl?: string;
		repository?: {
			id?: number;
			name?: string;
			nameWithOwner?: string;
			htmlUrl?: string;
		};
	};
	repositoryName?: string;
	score?: number;
}

export function ReviewActivityCard({
	isLoading,
	state = "UNKNOWN",
	submittedAt,
	htmlUrl,
	pullRequest,
	score,
}: ReviewActivityCardProps) {
	// Get the style for the current review state
	const stateStyle = REVIEW_STATE_STYLES[state] || REVIEW_STATE_STYLES.UNKNOWN;

	// Format relative time from submission date
	const relativeTime = submittedAt
		? formatDistanceToNow(submittedAt, { addSuffix: true })
		: undefined;

	// Use CSS to style the card as a clickable link with hover effects
	return (
		<a
			href={htmlUrl}
			target="_blank"
			rel="noopener noreferrer"
			className="block w-full"
		>
			<Card className="rounded-lg border border-border bg-card text-card-foreground shadow-sm hover:bg-accent/50 cursor-pointer">
				<div className="flex flex-col gap-1 px-6">
					{/* Repository, PR number and points */}
					<div className="flex justify-between gap-2 items-center text-sm text-github-muted-foreground">
						<span className="font-medium flex justify-center items-center space-x-1">
							{isLoading ? (
								<>
									<Skeleton
										className={cn("size-5", stateStyle.skeletonColor)}
									/>
									<Skeleton className="h-4 w-16 lg:w-36" />
								</>
							) : (
								<>
									<div className={stateStyle.color}>
										<stateStyle.icon className="mr-1" size={18} />
									</div>
									<span className="whitespace-nowrap">
										{pullRequest?.repository?.name} #{pullRequest?.number}{" "}
										{relativeTime}
									</span>
								</>
							)}
						</span>

						{!isLoading && score !== undefined && score > 0 && (
							<span className="flex items-center gap-1 text-github-done-foreground font-semibold">
								<Tooltip>
									<TooltipTrigger className="flex items-center gap-1">
										<AwardIcon size={16} />
										<span>+{score}</span>
									</TooltipTrigger>
									<TooltipContent side="top">
										Points awarded for this activity
									</TooltipContent>
								</Tooltip>
							</span>
						)}
					</div>

					{/* PR title */}
					<div className="flex justify-between font-medium contain-inline-size leading-normal">
						{isLoading ? (
							<Skeleton className="h-6 w-3/4" />
						) : (
							<FormattedTitle title={pullRequest?.title ?? ""} />
						)}
					</div>
				</div>
			</Card>
		</a>
	);
}

// webapp/src/app/user/review-activity-card/review-activity-card.component.ts
import { Component, computed, input } from '@angular/core';
import { PullRequestBaseInfo, PullRequestReviewInfo } from '@app/core/modules/openapi';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed } from '@ng-icons/octicons';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmSkeletonComponent } from '@spartan-ng/ui-skeleton-helm';
import { HlmIconComponent } from '@spartan-ng/ui-icon-helm';
import { HlmTooltipTriggerDirective } from '@spartan-ng/ui-tooltip-helm';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { lucideAward } from '@ng-icons/lucide';
import { cn } from '@app/utils';

dayjs.extend(relativeTime);

type ReviewStateCases = {
  [key: string]: {
    icon: string;
    color: string;
    skeletonColor: string;
  };
};

@Component({
  selector: 'app-review-activity-card',
  templateUrl: './review-activity-card.component.html',
  imports: [NgIcon, HlmCardModule, HlmSkeletonComponent, HlmIconComponent, HlmTooltipTriggerDirective, HlmButtonModule],
  providers: [provideIcons({ lucideAward })]
})
export class ReviewActivityCardComponent {
  protected readonly octCheck = octCheck;
  protected readonly octFileDiff = octFileDiff;
  protected readonly octComment = octComment;
  protected readonly octGitPullRequest = octGitPullRequest;
  protected readonly octGitPullRequestClosed = octGitPullRequestClosed;

  isLoading = input(false);
  class = input('');
  state = input<PullRequestReviewInfo.StateEnum>();
  submittedAt = input<string>();
  htmlUrl = input<string>();
  pullRequest = input<PullRequestBaseInfo>();
  repositoryName = input<string>();
  score = input<number>();

  computedClass = computed(() => cn('flex flex-col gap-1 p-6 hover:bg-accent/50 container-inline-size', this.class()));
  relativeActivityTime = computed(() => dayjs(this.submittedAt()).fromNow());
  displayPullRequestTitle = computed(() => (this.pullRequest()?.title ?? '').replace(/`([^`]+)`/g, '<code class="textCode">$1</code>'));

  reviewStateCases: ReviewStateCases = {
    [PullRequestReviewInfo.StateEnum.Approved]: {
      icon: this.octCheck,
      color: 'text-github-success-foreground',
      skeletonColor: 'bg-green-500/30'
    },
    [PullRequestReviewInfo.StateEnum.ChangesRequested]: {
      icon: this.octFileDiff,
      color: 'text-github-danger-foreground',
      skeletonColor: 'bg-destructive/20'
    },
    [PullRequestReviewInfo.StateEnum.Commented]: {
      icon: this.octComment,
      color: 'text-github-neutral-foreground',
      skeletonColor: 'bg-neutral-500/20'
    }
  };

  skeletonColorForReviewState = computed(() => {
    if (this.isLoading()) {
      const colors = Object.values(this.reviewStateCases).map((value) => value.skeletonColor);
      return colors[Math.floor(Math.random() * colors.length)];
    }
    return '';
  });

  reviewStateProps = computed(() => {
    const props = this.state() ? this.reviewStateCases[this.state()!] : undefined;
    return props ?? this.reviewStateCases[PullRequestReviewInfo.StateEnum.Commented];
  });
}

@if (isLoading()) {
  <div hlmCard [class]="class()">
    <div hlmCardContent>
      <hlm-skeleton class="h-4 w-1/2"></hlm-skeleton>
      <div class="flex items-center gap-2 font-medium">
        <hlm-skeleton [class]="'h-7 w-7 ' + this.skeletonColorForReviewState()"></hlm-skeleton>
        <hlm-skeleton class="h-6 w-3/4"></hlm-skeleton>
      </div>
    </div>
  </div>
} @else {
  <a hlmCard class="hover:bg-accent/50" [href]="htmlUrl() ?? this.pullRequest()?.htmlUrl" target="_blank" rel="noopener noreferrer" [class]="class()">
    <div hlmCardContent>
      <div class="flex items-center justify-between">
        <span class="text-sm text-muted-foreground first-letter:uppercase">
          {{ relativeActivityTime() }}
          in
          {{ this.repositoryName() }} #{{ this.pullRequest()?.number }}
        </span>
        <button
          hlmBtn
          [hlmTooltipTrigger]="'Points awarded for this activity'"
          variant="ghost"
          size="sm"
          aria-describedby="Points Activity"
          class="flex items-center text-github-done-foreground h-8"
        >
          <hlm-icon size="sm" name="lucideAward" />
          <span>+{{ this.score() }}</span>
        </button>
      </div>
      <div class="containerSize flex items-center gap-2 font-medium">
        <ng-icon [className]="this.reviewStateProps().color" [svg]="this.reviewStateProps().icon" size="20"></ng-icon>
        <span [innerHTML]="displayPullRequestTitle()" class="truncate w-[95%]"></span>
      </div>
    </div>
  </a>
}
