// webapp-react/src/features/profile/components/ReviewActivityCard.tsx
import { formatDistanceToNow, parseISO } from "date-fns";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import {
  CheckIcon,
  CommentIcon,
  FileDiffIcon,
  GitPullRequestIcon,
} from "@primer/octicons-react";
import type { ReviewActivityCardProps } from "../types";
import { cn } from "@/lib/utils";

// Define the styling for different review states
const REVIEW_STATE_STYLES: Record<
  string,
  { icon: React.ElementType; color: string; skeletonColor: string; tooltip: string }
> = {
  APPROVED: {
    icon: CheckIcon,
    color: "text-github-success-foreground",
    skeletonColor: "bg-github-success-foreground/30",
    tooltip: "Approved",
  },
  CHANGES_REQUESTED: {
    icon: FileDiffIcon,
    color: "text-github-danger-foreground",
    skeletonColor: "bg-github-danger-foreground/30",
    tooltip: "Changes Requested",
  },
  COMMENTED: {
    icon: CommentIcon,
    color: "text-github-muted-foreground",
    skeletonColor: "bg-github-muted-foreground/30",
    tooltip: "Commented",
  },
  UNKNOWN: {
    icon: GitPullRequestIcon,
    color: "text-github-muted-foreground",
    skeletonColor: "bg-github-muted-foreground/30",
    tooltip: "Reviewed",
  },
};

export function ReviewActivityCard({
  isLoading,
  state = "UNKNOWN",
  submittedAt,
  htmlUrl,
  pullRequest,
  score,
}: ReviewActivityCardProps) {
  // Get the style for the current review state
  const stateStyle = REVIEW_STATE_STYLES[state] || REVIEW_STATE_STYLES.UNKNOWN;

  // Format relative time from submission date
  const relativeTime = submittedAt
    ? formatDistanceToNow(parseISO(submittedAt), { addSuffix: true })
    : undefined;

  return (
    <Card
      className={cn(
        "overflow-hidden transition-colors border-l-4",
        isLoading
          ? `border-l-${stateStyle.skeletonColor}`
          : `border-l-${stateStyle.color.replace("text-", "")}`
      )}
    >
      <CardContent className="p-4">
        {isLoading ? (
          <div className="flex flex-col gap-2">
            <div className="flex justify-between items-center">
              <Skeleton className="h-6 w-40" />
              <Skeleton className="h-6 w-20" />
            </div>
            <Skeleton className="h-4 w-full" />
            <div className="flex justify-between items-center mt-1">
              <Skeleton className="h-5 w-32" />
              <Skeleton className="h-5 w-16" />
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-1">
            {/* Repository and PR number */}
            <div className="flex justify-between items-center">
              <div className="flex items-center gap-2">
                <Tooltip>
                  <TooltipTrigger asChild>
                    <div className={cn("flex items-center", stateStyle.color)}>
                      <stateStyle.icon size={18} />
                    </div>
                  </TooltipTrigger>
                  <TooltipContent side="top">{stateStyle.tooltip}</TooltipContent>
                </Tooltip>
                <a
                  href={htmlUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-medium hover:underline"
                >
                  {pullRequest?.repository?.name} #{pullRequest?.number}
                </a>
              </div>
              {score !== undefined && score > 0 && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <div className="flex items-center gap-1 text-github-accent-foreground font-semibold">
                      +{score}
                    </div>
                  </TooltipTrigger>
                  <TooltipContent side="top">Points earned for this review</TooltipContent>
                </Tooltip>
              )}
            </div>

            {/* PR title */}
            <a
              href={htmlUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              {pullRequest?.title}
            </a>

            {/* Relative time */}
            <div className="flex justify-between items-center mt-1">
              <span className="text-xs text-muted-foreground">{relativeTime}</span>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// webapp/src/app/user/review-activity-card/review-activity-card.component.ts
import { Component, computed, input } from '@angular/core';
import { PullRequestBaseInfo, PullRequestReviewInfo } from '@app/core/modules/openapi';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed } from '@ng-icons/octicons';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmSkeletonComponent } from '@spartan-ng/ui-skeleton-helm';
import { HlmIconComponent } from '@spartan-ng/ui-icon-helm';
import { HlmTooltipTriggerDirective } from '@spartan-ng/ui-tooltip-helm';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
import { lucideAward } from '@ng-icons/lucide';
import { cn } from '@app/utils';

dayjs.extend(relativeTime);

type ReviewStateCases = {
  [key: string]: {
    icon: string;
    color: string;
    skeletonColor: string;
  };
};

@Component({
  selector: 'app-review-activity-card',
  templateUrl: './review-activity-card.component.html',
  imports: [NgIcon, HlmCardModule, HlmSkeletonComponent, HlmIconComponent, HlmTooltipTriggerDirective, HlmButtonModule],
  providers: [provideIcons({ lucideAward })]
})
export class ReviewActivityCardComponent {
  protected readonly octCheck = octCheck;
  protected readonly octFileDiff = octFileDiff;
  protected readonly octComment = octComment;
  protected readonly octGitPullRequest = octGitPullRequest;
  protected readonly octGitPullRequestClosed = octGitPullRequestClosed;

  isLoading = input(false);
  class = input('');
  state = input<PullRequestReviewInfo.StateEnum>();
  submittedAt = input<string>();
  htmlUrl = input<string>();
  pullRequest = input<PullRequestBaseInfo>();
  repositoryName = input<string>();
  score = input<number>();

  computedClass = computed(() => cn('flex flex-col gap-1 p-6 hover:bg-accent/50 container-inline-size', this.class()));
  relativeActivityTime = computed(() => dayjs(this.submittedAt()).fromNow());
  displayPullRequestTitle = computed(() => (this.pullRequest()?.title ?? '').replace(/`([^`]+)`/g, '<code class="textCode">$1</code>'));

  reviewStateCases: ReviewStateCases = {
    [PullRequestReviewInfo.StateEnum.Approved]: {
      icon: this.octCheck,
      color: 'text-github-success-foreground',
      skeletonColor: 'bg-green-500/30'
    },
    [PullRequestReviewInfo.StateEnum.ChangesRequested]: {
      icon: this.octFileDiff,
      color: 'text-github-danger-foreground',
      skeletonColor: 'bg-destructive/20'
    },
    [PullRequestReviewInfo.StateEnum.Commented]: {
      icon: this.octComment,
      color: 'text-github-neutral-foreground',
      skeletonColor: 'bg-neutral-500/20'
    }
  };

  skeletonColorForReviewState = computed(() => {
    if (this.isLoading()) {
      const colors = Object.values(this.reviewStateCases).map((value) => value.skeletonColor);
      return colors[Math.floor(Math.random() * colors.length)];
    }
    return '';
  });

  reviewStateProps = computed(() => {
    const props = this.state() ? this.reviewStateCases[this.state()!] : undefined;
    return props ?? this.reviewStateCases[PullRequestReviewInfo.StateEnum.Commented];
  });
}

@if (isLoading()) {
  <div hlmCard [class]="class()">
    <div hlmCardContent>
      <hlm-skeleton class="h-4 w-1/2"></hlm-skeleton>
      <div class="flex items-center gap-2 font-medium">
        <hlm-skeleton [class]="'h-7 w-7 ' + this.skeletonColorForReviewState()"></hlm-skeleton>
        <hlm-skeleton class="h-6 w-3/4"></hlm-skeleton>
      </div>
    </div>
  </div>
} @else {
  <a hlmCard class="hover:bg-accent/50" [href]="htmlUrl() ?? this.pullRequest()?.htmlUrl" target="_blank" rel="noopener noreferrer" [class]="class()">
    <div hlmCardContent>
      <div class="flex items-center justify-between">
        <span class="text-sm text-muted-foreground first-letter:uppercase">
          {{ relativeActivityTime() }}
          in
          {{ this.repositoryName() }} #{{ this.pullRequest()?.number }}
        </span>
        <button
          hlmBtn
          [hlmTooltipTrigger]="'Points awarded for this activity'"
          variant="ghost"
          size="sm"
          aria-describedby="Points Activity"
          class="flex items-center text-github-done-foreground h-8"
        >
          <hlm-icon size="sm" name="lucideAward" />
          <span>+{{ this.score() }}</span>
        </button>
      </div>
      <div class="containerSize flex items-center gap-2 font-medium">
        <ng-icon [className]="this.reviewStateProps().color" [svg]="this.reviewStateProps().icon" size="20"></ng-icon>
        <span [innerHTML]="displayPullRequestTitle()" class="truncate w-[95%]"></span>
      </div>
    </div>
  </a>
}
