// webapp/src/app/home/leaderboard/reviews-popover/reviews-popover.component.ts
import { Component, computed, input, signal } from '@angular/core';
import { octGitPullRequest } from '@ng-icons/octicons';
import { lucideClipboardCopy, lucideCheck } from '@ng-icons/lucide';
import { HlmPopoverModule } from '@spartan-ng/ui-popover-helm';
import { BrnPopoverComponent, BrnPopoverContentDirective, BrnPopoverTriggerDirective } from '@spartan-ng/brain/popover';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { NgScrollbarModule } from 'ngx-scrollbar';
import { HlmScrollAreaDirective } from '@spartan-ng/ui-scrollarea-helm';

export interface PullRequestInfo {
  id: number;
  repository?: {
    name: string;
  };
  number: number;
  title: string;
  htmlUrl: string;
}

@Component({
  selector: 'app-reviews-popover',
  imports: [
    HlmPopoverModule,
    BrnPopoverComponent,
    BrnPopoverContentDirective,
    BrnPopoverTriggerDirective,
    HlmButtonModule,
    NgIconComponent,
    NgScrollbarModule,
    HlmScrollAreaDirective,
    HlmScrollAreaDirective
  ],
  providers: [provideIcons({ octGitPullRequest, lucideCheck, lucideClipboardCopy })],
  templateUrl: './reviews-popover.component.html'
})
export class ReviewsPopoverComponent {
  highlight = input.required<boolean>();
  reviewedPRs = input.required<PullRequestInfo[]>();

  sortedReviewedPRs = computed(() =>
    this.reviewedPRs().sort((a, b) => {
      if (a.repository?.name === b.repository?.name) {
        return a.number - b.number;
      }
      return (a.repository?.name ?? '').localeCompare(b.repository?.name ?? '');
    })
  );
  showCopySuccess = signal(false);

  private timeoutShowCopySuccess: ReturnType<typeof setTimeout> | undefined;

  copyPullRequests() {
    const htmlList = `<ul>
      ${this.sortedReviewedPRs()
        .map((pullRequest) => `<li><a href="${pullRequest.htmlUrl}">${pullRequest.repository?.name ?? ''} #${pullRequest.number}</a></li>`)
        .join('\n')}
    </ul>`;

    // As markdown text
    const plainText = this.sortedReviewedPRs()
      .map((pullRequest) => `[${pullRequest.repository?.name ?? ''} #${pullRequest.number}](${pullRequest.htmlUrl})`)
      .join('\n');

    const clipboardItem = new ClipboardItem({
      'text/html': new Blob([htmlList], { type: 'text/html' }),
      'text/plain': new Blob([plainText], { type: 'text/plain' })
    });

    navigator.clipboard.write([clipboardItem]).catch(() => {
      // Fallback to plain text if html copying fails
      navigator.clipboard.writeText(plainText);
    });

    this.showCopySuccess.set(true);

    if (this.timeoutShowCopySuccess) {
      clearTimeout(this.timeoutShowCopySuccess);
    }
    this.timeoutShowCopySuccess = setTimeout(() => {
      this.showCopySuccess.set(false);
    }, 2000);
  }
}

<brn-popover sideOffset="5" closeDelay="100">
  <button
    [variant]="highlight() ? 'outline' : 'outline'"
    size="sm"
    [class]="'flex items-center gap-1 ' + (!highlight() ? 'text-github-muted-foreground' : 'border-primary bg-accent hover:bg-primary hover:text-background')"
    brnPopoverTrigger
    hlmBtn
    (click)="$event.stopPropagation()"
    [disabled]="!reviewedPRs().length"
  >
    <ng-icon name="octGitPullRequest" size="16" />
    {{ reviewedPRs().length }}
  </button>
  <div hlmPopoverContent class="space-y-2 w-60" *brnPopoverContent="let ctx">
    <div class="flex flex-wrap justify-between items-center gap-4">
      <div class="flex items-center gap-2">
        <ng-icon name="octGitPullRequest" size="20" />
        <h4 class="font-medium leading-none">Reviewed PRs</h4>
      </div>
      <button hlmBtn variant="outline" size="icon" (click)="copyPullRequests()">
        @if (showCopySuccess()) {
          <ng-icon name="lucideCheck" class="text-green-600 size-5" />
        } @else {
          <ng-icon name="lucideClipboardCopy" class="size-5" />
        }
      </button>
    </div>
    <ng-scrollbar hlm class="-mr-2.5" [style]="'height: min(200px, calc(' + 42 * reviewedPRs().length + 'px))'">
      <div class="flex flex-col rounded-md text-muted-foreground text-sm pr-2.5">
        @for (pullRequest of sortedReviewedPRs(); track pullRequest.id) {
          <a hlmBtn [href]="pullRequest.htmlUrl" target="_blank" variant="ghost" class="justify-start" [title]="pullRequest.title">
            {{ pullRequest.repository?.name ?? '' }} #{{ pullRequest.number }}
          </a>
        }
      </div>
    </ng-scrollbar>
  </div>
</brn-popover>

// webapp/src/components/leaderboard/ReviewsPopover.tsx
import {
	CheckIcon,
	CopyIcon,
	GitPullRequestIcon,
} from "@primer/octicons-react";
import { useEffect, useState } from "react";
import type { PullRequestBaseInfo, PullRequestInfo } from "@/api/types.gen";
import { Button } from "@/components/ui/button";
import { CardTitle } from "@/components/ui/card";
import {
	Popover,
	PopoverContent,
	PopoverTrigger,
} from "@/components/ui/popover";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";

export type ReviewedPullRequest = PullRequestInfo | PullRequestBaseInfo;

export interface ReviewsPopoverProps {
	reviewedPRs: readonly ReviewedPullRequest[];
	highlight?: boolean;
}

export function ReviewsPopover({
	reviewedPRs,
	highlight = false,
}: ReviewsPopoverProps) {
	const [isOpen, setIsOpen] = useState(false);
	const [showCopySuccess, setShowCopySuccess] = useState(false);
	const hasReviews = reviewedPRs?.length > 0;

	// Sort reviewed PRs by repository name and PR number
	const sortedReviewedPRs = reviewedPRs
		? [...reviewedPRs].sort((a, b) => {
				if (a.repository?.name === b.repository?.name) {
					return a.number - b.number;
				}
				return (a.repository?.name ?? "").localeCompare(
					b.repository?.name ?? "",
				);
			})
		: [];

	// Helper function to copy PR URLs to clipboard
	const copyPullRequests = () => {
		if (!hasReviews) return;

		// Create HTML for clipboard
		const htmlList = `<ul>
      ${sortedReviewedPRs
				.map(
					(pullRequest) =>
						`<li><a href="${pullRequest.htmlUrl}">${pullRequest.repository?.name ?? ""} #${pullRequest.number}</a></li>`,
				)
				.join("\n")}
    </ul>`;

		// Create markdown text
		const plainText = sortedReviewedPRs
			.map(
				(pullRequest) =>
					`[${pullRequest.repository?.name ?? ""} #${pullRequest.number}](${pullRequest.htmlUrl})`,
			)
			.join("\n");

		try {
			// Try to use the ClipboardItem API (modern browsers)
			const clipboardItem = new ClipboardItem({
				"text/html": new Blob([htmlList], { type: "text/html" }),
				"text/plain": new Blob([plainText], { type: "text/plain" }),
			});

			navigator.clipboard.write([clipboardItem]).catch(() => {
				// Fallback to plain text if html copying fails
				navigator.clipboard.writeText(plainText);
			});
		} catch (_e) {
			// Basic fallback for older browsers
			navigator.clipboard.writeText(plainText);
		}

		// Show success indication
		setShowCopySuccess(true);

		// Reset the success indicator after 2 seconds
		setTimeout(() => {
			setShowCopySuccess(false);
		}, 2000);
	};

	// Clear timeout when component unmounts
	useEffect(() => {
		return () => {
			if (showCopySuccess) {
				setShowCopySuccess(false);
			}
		};
	}, [showCopySuccess]);

	return (
		<Popover open={isOpen} onOpenChange={setIsOpen}>
			<PopoverTrigger asChild>
				<Button
					variant="outline"
					size="sm"
					disabled={!hasReviews}
					className={cn(
						"flex items-center gap-1",
						!highlight
							? "text-github-muted-foreground"
							: "border-primary bg-accent hover:bg-foreground hover:text-background",
					)}
					onClick={(e) => e.stopPropagation()}
				>
					<GitPullRequestIcon size={16} />
					{reviewedPRs?.length || 0}
				</Button>
			</PopoverTrigger>
			<PopoverContent
				className="space-y-2 w-60"
				sideOffset={5}
				onClick={(e) => e.stopPropagation()}
			>
				<div className="flex flex-wrap justify-between items-center gap-4">
					<CardTitle className="flex items-center gap-2">
						<GitPullRequestIcon size={20} />
						<h4 className="font-medium leading-none">Reviewed PRs</h4>
					</CardTitle>
					<Button variant="outline" size="icon" onClick={copyPullRequests}>
						{showCopySuccess ? (
							<CheckIcon className="text-green-600 size-4" />
						) : (
							<CopyIcon className="size-4" />
						)}
					</Button>
				</div>
				{hasReviews && (
					<ScrollArea
						className="rounded-md -mr-2.5"
						style={{
							height: `min(200px, ${36 * sortedReviewedPRs.length}px)`,
						}}
					>
						<div className="flex flex-col rounded-md text-muted-foreground text-sm pr-2.5">
							{sortedReviewedPRs.map((pullRequest) => (
								<a
									key={pullRequest.id}
									href={pullRequest.htmlUrl}
									target="_blank"
									rel="noopener noreferrer"
									className={cn(
										"px-3 py-2 hover:bg-accent rounded-md justify-start",
										"transition-colors duration-200",
									)}
									title={pullRequest.title}
								>
									{pullRequest.repository?.name ?? ""} #{pullRequest.number}
								</a>
							))}
						</div>
					</ScrollArea>
				)}
			</PopoverContent>
		</Popover>
	);
}
