// webapp/src/app/user/issue-card/issue-card.component.ts
import { Component, computed, input } from '@angular/core';
import { PullRequestInfo, LabelInfo } from '@app/core/modules/openapi';
import { NgIcon } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed, octGitPullRequestDraft, octGitMerge, octX } from '@ng-icons/octicons';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmSkeletonComponent } from '@spartan-ng/ui-skeleton-helm';
import { GithubLabelComponent } from '@app/ui/github-label/github-label.component';
import dayjs from 'dayjs/esm';
import { cn } from '@app/utils';
import { formatTitle } from '@app/utils';
@Component({
  selector: 'app-issue-card',
  templateUrl: './issue-card.component.html',
  imports: [NgIcon, HlmCardModule, HlmSkeletonComponent, GithubLabelComponent]
})
export class IssueCardComponent {
  protected readonly octCheck = octCheck;
  protected readonly octX = octX;
  protected readonly octComment = octComment;
  protected readonly octFileDiff = octFileDiff;

  isLoading = input(false);
  class = input('');
  title = input<string>();
  number = input<number>();
  additions = input<number>();
  deletions = input<number>();
  htmlUrl = input<string>();
  repositoryName = input<string>();
  createdAt = input<string>();
  state = input<PullRequestInfo.StateEnum>();
  isDraft = input<boolean>();
  isMerged = input<boolean>();
  pullRequestLabels = input<Array<LabelInfo>>();

  displayCreated = computed(() => dayjs(this.createdAt()));
  displayTitle = computed(() => formatTitle(this.title() ?? ''));
  computedClass = computed(() => cn('flex flex-col gap-1 pt-6 w-72', !this.isLoading() ? 'hover:bg-accent/50 cursor-pointer' : '', this.class()));

  issueIconAndColor = computed(() => {
    var icon: string;
    var color: string;

    if (this.state() === PullRequestInfo.StateEnum.Open) {
      if (this.isDraft()) {
        icon = octGitPullRequestDraft;
        color = 'text-github-muted-foreground';
      } else {
        icon = octGitPullRequest;
        color = 'text-github-open-foreground';
      }
    } else {
      if (this.isMerged()) {
        icon = octGitMerge;
        color = 'text-github-done-foreground';
      } else {
        icon = octGitPullRequestClosed;
        color = 'text-github-closed-foreground';
      }
    }

    return { icon, color };
  });
}

<a hlmCard variant="profile" [class]="computedClass()" [href]="url()" target="_blank" rel="noopener noreferrer">
  <div hlmCardContent variant="profile">
    <div class="flex justify-between items-center text-sm text-github-muted-foreground">
      <span class="font-medium flex justify-center items-center space-x-1">
        @if (isLoading()) {
          <hlm-skeleton class="size-5 bg-green-500/30"></hlm-skeleton>
          <hlm-skeleton class="h-4 w-16 lg:w-36"></hlm-skeleton>
        } @else {
          @if (state() === 'OPEN') {
            <ng-icon [svg]="octGitPullRequest" size="18" class="mr-1 text-github-success-foreground"></ng-icon>
          } @else {
            <ng-icon [svg]="octGitPullRequestClosed" size="18" class="mr-1 text-github-danger-foreground"></ng-icon>
          }

          {{ repositoryName() }} #{{ number() }} on {{ displayCreated().format('MMM D') }}
        }
      </span>
      <span class="flex items-center space-x-2">
        @if (isLoading()) {
          <hlm-skeleton class="h-4 w-8 bg-green-500/30"></hlm-skeleton>
          <hlm-skeleton class="h-4 w-8 bg-destructive/20"></hlm-skeleton>
        } @else {
          <span class="text-github-success-foreground font-bold">+{{ additions() }}</span>
          <span class="text-github-danger-foreground font-bold">-{{ deletions() }}</span>
        }
      </span>
    </div>

    <span class="containerSize flex justify-between font-medium mb-3">
      @if (isLoading()) {
        <hlm-skeleton class="h-6 w-3/4"></hlm-skeleton>
      } @else {
        <div [innerHTML]="displayTitle()" class="truncate"></div>
      }
    </span>
  </div>
  @if (!isLoading()) {
    <div hlmCardFooter class="flex flex-wrap gap-2 p-0 space-x-0">
      @for (label of pullRequestLabels(); track label.name) {
        @let labelColors = hexToRgb(label.color ?? 'FFFFFF');
        <span
          class="px-2 py-0.5 rounded-[2rem] text-xs font-medium dark:border gh-label"
          [style.--label-r]="labelColors.r"
          [style.--label-g]="labelColors.g"
          [style.--label-b]="labelColors.b"
          [style.--label-h]="labelColors.h"
          [style.--label-s]="labelColors.s"
          [style.--label-l]="labelColors.l"
        >
          {{ label.name }}
        </span>
      }
    </div>
  }
</a>

// webapp-react/src/components/profile/IssueCard.tsx
import type { LabelInfo } from "@/api/types.gen";
import { FormattedTitle } from "@/components/shared/FormattedTitle";
import { GithubBadge } from "@/components/shared/GithubBadge";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import {
	GitMergeIcon,
	GitPullRequestClosedIcon,
	GitPullRequestDraftIcon,
	GitPullRequestIcon,
} from "@primer/octicons-react";
import { format, parseISO } from "date-fns";

export interface IssueCardProps {
	isLoading: boolean;
	title?: string;
	number?: number;
	additions?: number;
	deletions?: number;
	htmlUrl?: string;
	repositoryName?: string;
	createdAt?: string;
	state?: "OPEN" | "CLOSED";
	isDraft?: boolean;
	isMerged?: boolean;
	pullRequestLabels?: LabelInfo[];
}

export function IssueCard({
	isLoading,
	title,
	number,
	additions,
	deletions,
	htmlUrl,
	repositoryName,
	createdAt,
	state,
	isDraft,
	isMerged,
	pullRequestLabels = [],
}: IssueCardProps) {
	// Determine the PR state icon and color
	const getIssueIconAndColor = () => {
		if (state === "OPEN") {
			if (isDraft) {
				return {
					icon: GitPullRequestDraftIcon,
					color: "text-github-muted-foreground",
				};
			}
			return { icon: GitPullRequestIcon, color: "text-github-open-foreground" };
		}
		if (isMerged) {
			return { icon: GitMergeIcon, color: "text-github-done-foreground" };
		}
		return {
			icon: GitPullRequestClosedIcon,
			color: "text-github-closed-foreground",
		};
	};

	const { icon: StateIcon, color } = getIssueIconAndColor();

	// Format the date as MMM D (e.g., "Jan 15")
	const formattedDate = createdAt ? format(parseISO(createdAt), "MMM d") : "";

	// Use CSS to style the card as a clickable link with hover effects
	return (
		<a
			href={htmlUrl}
			target="_blank"
			rel="noopener noreferrer"
			className="block w-full"
		>
			<Card className="rounded-lg border border-border bg-card text-card-foreground shadow-sm hover:bg-accent/50 cursor-pointer py-0 gap-0">
				<div
					className={cn("flex flex-col gap-1 p-6", {
						"pb-0": isLoading || pullRequestLabels.length > 0,
					})}
				>
					<div className="flex justify-between gap-2 items-center text-sm text-github-muted-foreground">
						<span className="font-medium flex justify-center items-center space-x-1">
							{isLoading ? (
								<>
									<Skeleton className="size-5 bg-green-500/30" />
									<Skeleton className="h-4 w-16 lg:w-36" />
								</>
							) : (
								<>
									<StateIcon className={`mr-2 ${color}`} size={18} />
									<span className="whitespace-nowrap">
										{repositoryName} #{number} on {formattedDate}
									</span>
								</>
							)}
						</span>
						<span className="flex items-center space-x-2">
							{isLoading ? (
								<>
									<Skeleton className="h-4 w-8 bg-green-500/30" />
									<Skeleton className="h-4 w-8 bg-destructive/20" />
								</>
							) : (
								<>
									{additions !== undefined && (
										<span className="text-github-success-foreground font-bold">
											+{additions}
										</span>
									)}
									{deletions !== undefined && (
										<span className="text-github-danger-foreground font-bold">
											-{deletions}
										</span>
									)}
								</>
							)}
						</span>
					</div>

					<div className="flex justify-between font-medium contain-inline-size leading-normal">
						{isLoading ? (
							<Skeleton className="h-6 w-3/4 mb-6" />
						) : (
							<FormattedTitle title={title ?? ""} />
						)}
					</div>
				</div>

				{pullRequestLabels.length > 0 && (
					<div className="flex flex-row items-center flex-wrap gap-2 p-6 pt-2">
						{pullRequestLabels.map((label) => (
							<GithubBadge
								key={label.id}
								label={label.name}
								color={label.color}
							/>
						))}
					</div>
				)}
			</Card>
		</a>
	);
}
