// webapp/src/app/core/IssueCard/issue-card.component.ts
import { Component, input } from '@angular/core';
import { PullRequest, PullRequestLabel, PullRequestReview } from '@app/core/modules/openapi';
import { NgIcon } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed, octX } from '@ng-icons/octicons';
import { Dayjs } from 'dayjs';
import { NgStyle } from '@angular/common';

@Component({
  selector: 'app-issue-card',
  templateUrl: './issue-card.component.html',
  imports: [NgIcon, NgStyle],
  standalone: true
})
export class IssueCardComponent {
  title = input.required<string>();
  number = input.required<number>();
  additions = input.required<number>();
  deletions = input.required<number>();
  url = input.required<string>();
  repositoryName = input.required<string>();
  reviews = input.required<Array<PullRequestReview>>();
  createdAt = input.required<Dayjs>();
  state = input.required<PullRequest.StateEnum>();
  pullRequestLabels = input.required<Array<PullRequestLabel>>();
  protected readonly octCheck = octCheck;
  protected readonly octX = octX;
  protected readonly octComment = octComment;
  protected readonly octGitPullRequest = octGitPullRequest;
  protected readonly octFileDiff = octFileDiff;
  protected readonly octGitPullRequestClosed = octGitPullRequestClosed;

  getMostRecentReview() {
    return this.reviews().reduce((latest, review) => {
      return new Date(review.updatedAt || 0) > new Date(latest.updatedAt || 0) ? review : latest;
    });
  }

  openIssue() {
    window.open(this.url());
  }
}

<div class="border border-border bg-card rounded-lg p-4 w-72">
  <div class="flex justify-between items-center mb-2 text-xs text-gray-500">
    <span class="font-bold flex justify-center items-center space-x-1">
      @if (state() === 'OPEN') {
        <ng-icon [svg]="octGitPullRequest" size="16" class="mr-1 text-github-success-foreground"></ng-icon>
      } @else {
        <ng-icon [svg]="octGitPullRequestClosed" size="16" class="mr-1 text-github-danger-foreground"></ng-icon>
      }

      {{ repositoryName() }} #{{ number() }} on {{ createdAt().format('MMM D') }}
    </span>
    <span class="flex items-center space-x-2">
      <span class="text-github-success-foreground font-bold">+{{ additions() }}</span>
      <span class="text-github-danger-foreground font-bold">-{{ deletions() }}</span>
    </span>
  </div>

  <div class="flex justify-between font-bold text-sm mb-3 hover:text-github-accent-foreground cursor-pointer" (click)="openIssue()">
    {{ title() }}
    @if (getMostRecentReview(); as review) {
      @if (review.state === 'APPROVED') {
        <ng-icon [svg]="octCheck" size="16" class="text-github-success-foreground"></ng-icon>
      } @else if (review.state === 'DISMISSED') {
        <ng-icon [svg]="octX" size="16" class="text-github-danger-foreground"></ng-icon>
      } @else if (review.state === 'COMMENTED') {
        <ng-icon [svg]="octComment" size="16" class="text-github-muted-foreground"></ng-icon>
      } @else {
        <ng-icon [svg]="octFileDiff" size="16" class="text-github-danger-foreground"></ng-icon>
      }
    }
  </div>
  <div class="flex gap-1 flex-wrap">
    @for (label of pullRequestLabels(); track label.name) {
      <span class="px-2 py-1 rounded-full text-xs mr-2 text-neutral-100/95" [style.background-color]="label.color">{{ label.name }}</span>
    }
  </div>
</div>

// webapp-react/src/components/profile/IssueCard.tsx
import type { LabelInfo } from "@/api/types.gen";
import { FormattedTitle } from "@/components/shared/FormattedTitle";
import { GithubBadge } from "@/components/shared/GithubBadge";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import {
	GitMergeIcon,
	GitPullRequestClosedIcon,
	GitPullRequestDraftIcon,
	GitPullRequestIcon,
} from "@primer/octicons-react";
import { format, parseISO } from "date-fns";

export interface IssueCardProps {
	isLoading: boolean;
	title?: string;
	number?: number;
	additions?: number;
	deletions?: number;
	htmlUrl?: string;
	repositoryName?: string;
	createdAt?: string;
	state?: "OPEN" | "CLOSED";
	isDraft?: boolean;
	isMerged?: boolean;
	pullRequestLabels?: LabelInfo[];
}

export function IssueCard({
	isLoading,
	title,
	number,
	additions,
	deletions,
	htmlUrl,
	repositoryName,
	createdAt,
	state,
	isDraft,
	isMerged,
	pullRequestLabels = [],
}: IssueCardProps) {
	// Determine the PR state icon and color
	const getIssueIconAndColor = () => {
		if (state === "OPEN") {
			if (isDraft) {
				return {
					icon: GitPullRequestDraftIcon,
					color: "text-github-muted-foreground",
				};
			}
			return { icon: GitPullRequestIcon, color: "text-github-open-foreground" };
		}
		if (isMerged) {
			return { icon: GitMergeIcon, color: "text-github-done-foreground" };
		}
		return {
			icon: GitPullRequestClosedIcon,
			color: "text-github-closed-foreground",
		};
	};

	const { icon: StateIcon, color } = getIssueIconAndColor();

	// Format the date as MMM D (e.g., "Jan 15")
	const formattedDate = createdAt ? format(parseISO(createdAt), "MMM d") : "";

	// Use CSS to style the card as a clickable link with hover effects
	return (
		<a
			href={htmlUrl}
			target="_blank"
			rel="noopener noreferrer"
			className="block w-full"
		>
			<Card className="rounded-lg border border-border bg-card text-card-foreground shadow-sm hover:bg-accent/50 cursor-pointer py-0 gap-0">
				<div
					className={cn("flex flex-col gap-1 p-6", {
						"pb-0": isLoading || pullRequestLabels.length > 0,
					})}
				>
					<div className="flex justify-between gap-2 items-center text-sm text-github-muted-foreground">
						<span className="font-medium flex justify-center items-center space-x-1">
							{isLoading ? (
								<>
									<Skeleton className="size-5 bg-green-500/30" />
									<Skeleton className="h-4 w-16 lg:w-36" />
								</>
							) : (
								<>
									<StateIcon className={`mr-2 ${color}`} size={18} />
									<span className="whitespace-nowrap">
										{repositoryName} #{number} on {formattedDate}
									</span>
								</>
							)}
						</span>
						<span className="flex items-center space-x-2">
							{isLoading ? (
								<>
									<Skeleton className="h-4 w-8 bg-green-500/30" />
									<Skeleton className="h-4 w-8 bg-destructive/20" />
								</>
							) : (
								<>
									{additions !== undefined && (
										<span className="text-github-success-foreground font-bold">
											+{additions}
										</span>
									)}
									{deletions !== undefined && (
										<span className="text-github-danger-foreground font-bold">
											-{deletions}
										</span>
									)}
								</>
							)}
						</span>
					</div>

					<div className="flex justify-between font-medium contain-inline-size leading-normal">
						{isLoading ? (
							<Skeleton className="h-6 w-3/4 mb-6" />
						) : (
							<FormattedTitle title={title ?? ""} />
						)}
					</div>
				</div>

				{pullRequestLabels.length > 0 && (
					<div className="flex flex-row items-center flex-wrap gap-2 p-6 pt-2">
						{pullRequestLabels.map((label) => (
							<GithubBadge
								key={label.id}
								label={label.name}
								color={label.color}
							/>
						))}
					</div>
				)}
			</Card>
		</a>
	);
}
