// webapp/src/app/mentor/sessions-card/sessions-card.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Plus } from 'lucide-angular';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { Session } from '@app/core/modules/openapi';

@Component({
  standalone: true,
  selector: 'app-sessions-card',
  templateUrl: './sessions-card.component.html',
  imports: [CommonModule, LucideAngularModule, HlmButtonModule]
})
export class SessionsCardComponent {
  protected Plus = Plus;

  sessions = input<Session[]>();
  activeSessionId = input<number | null>();

  sessionSelected = output<number>();
  createSession = output();

  handleSelectSession(sessionId: number): void {
    if (this.activeSessionId() && this.activeSessionId() !== sessionId) {
      this.sessionSelected.emit(sessionId);
    }
  }

  handleCreateSession(): void {
    this.createSession.emit();
  }
}

<div hlmCard class="flex flex-col px-6 lg:max-h-[calc(100dvh-200px)] pb-6 overflow-auto">
  @if (isLastSessionClosed()) {
    <button hlmBtn aria-describedby=">New Session" class="w-full gap-2 mt-6 justify-start h-9" (click)="this.createNewSession.emit()">
      <lucide-angular [img]="Plus" class="size-4" />
      <span>New Session</span>
    </button>
  } @else {
    <hlm-alert-dialog>
      <button hlmBtn brnAlertDialogTrigger aria-describedby=">New Session" class="w-full gap-2 mt-6 justify-start h-9">
        <lucide-angular [img]="Plus" class="size-4" />
        <span>New Session</span>
      </button>
      <hlm-alert-dialog-content *brnAlertDialogContent="let ctx">
        <hlm-alert-dialog-header>
          <h3 hlmAlertDialogTitle>Are you absolutely sure?</h3>
          <p hlmAlertDialogDescription>
            You have not finished your most recent session yet. If you start a new session, your current session will be closed. It may effect the quality of your mentorship.
          </p>
        </hlm-alert-dialog-header>
        <hlm-alert-dialog-footer>
          <button hlmAlertDialogCancel (click)="ctx.close()">Cancel</button>
          <button hlmAlertDialogAction (click)="ctx.close(); this.createNewSession.emit()">Start New Session</button>
        </hlm-alert-dialog-footer>
      </hlm-alert-dialog-content>
    </hlm-alert-dialog>
  }

  @if (isLoading()) {
    <div class="flex flex-col gap-2">
      <hlm-skeleton class="w-48 h-6 mt-6 pt-3" />
      <hlm-skeleton class="w-full h-9" />
      <hlm-skeleton class="w-full h-9" />
      <hlm-skeleton class="w-full h-9" />
      <hlm-skeleton class="w-full h-9" />
      <hlm-skeleton class="w-full h-9" />
    </div>
  } @else if ((sessions()?.length ?? 0) > 0) {
    <div class="flex flex-col gap-2">
      <h4 class="text-lg font-semibold mt-2 pt-3">Past Sessions</h4>
      @for (session of sessions(); track session.id) {
        <button brnToggle hlm [state]="selectedSessionId() === session.id ? 'on' : 'off'" (click)="selectedSessionId.set(session.id)" class="justify-start">
          {{ session.createdAt | date: 'short' }}
        </button>
      }
    </div>
  }
</div>

// webapp-react/src/components/old/mentor/SessionsCard.tsx
import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Toggle } from '@/components/ui/toggle';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

export interface Session {
  id: number;
  createdAt: string;
}

interface SessionsCardProps {
  sessions?: Session[];
  selectedSessionId?: number | null;
  onSessionSelect: (sessionId: number) => void;
  onCreateNewSession: () => void;
  isLoading?: boolean;
  isLastSessionClosed?: boolean;
}

export function SessionsCard({
  sessions = [],
  selectedSessionId = null,
  onSessionSelect,
  onCreateNewSession,
  isLoading = false,
  isLastSessionClosed = true,
}: SessionsCardProps) {
  return (
    <Card className="flex flex-col px-6 lg:max-h-[calc(100dvh-200px)] pb-6 overflow-auto">
      {isLastSessionClosed ? (
        <Button 
          onClick={onCreateNewSession} 
          className="w-full gap-2 mt-6 justify-start h-9"
          aria-label="New Session"
        >
          <Plus className="size-4" />
          <span>New Session</span>
        </Button>
      ) : (
        <AlertDialog>
          <AlertDialogTrigger asChild>
            <Button className="w-full gap-2 mt-6 justify-start h-9">
              <Plus className="size-4" />
              <span>New Session</span>
            </Button>
          </AlertDialogTrigger>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
              <AlertDialogDescription>
                You have not finished your most recent session yet. If you start a new session, 
                your current session will be closed. It may affect the quality of your mentorship.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={onCreateNewSession}>
                Start New Session
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      )}

      {isLoading ? (
        <div className="flex flex-col gap-2">
          <Skeleton className="w-48 h-6 mt-6 pt-3" />
          <Skeleton className="w-full h-9" />
          <Skeleton className="w-full h-9" />
          <Skeleton className="w-full h-9" />
          <Skeleton className="w-full h-9" />
          <Skeleton className="w-full h-9" />
        </div>
      ) : sessions.length > 0 ? (
        <div className="flex flex-col gap-2">
          <h4 className="text-lg font-semibold mt-2 pt-3">Past Sessions</h4>
          {sessions.map((session) => (
            <Toggle
              key={session.id}
              pressed={selectedSessionId === session.id}
              onPressedChange={() => onSessionSelect(session.id)}
              className="justify-start"
            >
              {new Date(session.createdAt).toLocaleString()}
            </Toggle>
          ))}
        </div>
      ) : null}
    </Card>
  );
}
