// webapp-react/src/components/Header.tsx
import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Hammer } from "lucide-react";

interface HeaderProps {
  onSignIn?: () => void;
  isSigningIn?: boolean;
  version?: string;
}

export default function Header({ onSignIn, isSigningIn = false, version = "v0.6.1" }: HeaderProps = {}) {
  const handleSignIn = onSignIn || (() => {
    const authUrl = `https://github.com/login/oauth/authorize?client_id=your_client_id&redirect_uri=${encodeURIComponent(window.location.origin)}`;
    window.location.href = authUrl;
  });

  // Placeholder for authentication state - in a real app, this would come from your auth provider
  const [isSignedIn, setIsSignedIn] = useState(false);
  const [user, setUser] = useState(null);

  return (
    <header className="container flex items-center justify-between pt-4 gap-2">
      <div className="flex gap-4 items-center flex-1">
        <div className="flex items-center gap-2">
          <Link className="flex gap-2 items-center hover:text-muted-foreground" to="/">
            <Hammer className="text-2xl sm:text-3xl" />
            <span className="hidden sm:inline-block text-xl font-semibold">Hephaestus</span>
          </Link>
          <span className="text-xs font-semibold mt-1 text-muted-foreground">{version}</span>
        </div>
        
        {isSignedIn && (
          <div className="hidden md:flex gap-2">
            <Button variant="link" asChild>
              <Link to="/workspace">Workspace</Link>
            </Button>
            <Button variant="link" asChild>
              <Link to={`/user/${user?.username}/activity`}>Activity</Link>
            </Button>
            <Button variant="link" asChild>
              <Link to="/teams">Teams</Link>
            </Button>
          </div>
        )}
      </div>
      
      <div className="flex items-center gap-2">
        {!isSignedIn && (
          <Button onClick={handleSignIn} disabled={isSigningIn}>
            {isSigningIn ? "Signing in..." : "Sign In"}
          </Button>
        )}
      </div>
    </header>
  );
}

// webapp/src/app/core/header/header.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideAngularModule, Hammer } from 'lucide-angular';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { SecurityStore } from '@app/core/security/security-store.service';
import { ThemeSwitcherComponent } from '@app/core/theme/theme-switcher.component';
import { RequestFeatureComponent } from './request-feature/request-feature.component';
import { environment } from 'environments/environment';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  standalone: true,
  imports: [RouterLink, LucideAngularModule, ThemeSwitcherComponent, HlmButtonModule, RequestFeatureComponent]
})
export class HeaderComponent {
  protected Hammer = Hammer;

  securityStore = inject(SecurityStore);
  signedIn = this.securityStore.signedIn;

  protected signOut() {
    this.securityStore.signOut();
  }

  protected signIn() {
    if (environment.keycloak.skipLoginPage) {
      const authUrl =
        `${environment.keycloak.url}/realms/${environment.keycloak.realm}/protocol/openid-connect/auth` +
        `?client_id=${encodeURIComponent(environment.keycloak.clientId)}` +
        `&redirect_uri=${encodeURIComponent(environment.clientUrl)}` +
        `&response_type=code` +
        `&scope=openid` +
        `&kc_idp_hint=${encodeURIComponent('github')}`;

      // Redirect the user to the Keycloak GitHub login
      window.location.href = authUrl;
    } else {
      this.securityStore.signIn();
    }
  }
}

<header class="container flex items-center justify-between pt-4 gap-2">
  <div class="flex gap-4 items-center flex-1">
    <div class="flex items-center gap-2">
      <a class="flex gap-2 items-center hover:text-muted-foreground" routerLink="/">
        <lucide-angular [img]="Hammer" class="size-8 sm:size-6" />
        <span class="hidden sm:inline-block text-xl font-semibold">Hephaestus</span>
      </a>
      <span class="text-xs font-semibold mt-1 text-muted-foreground">{{ version }}</span>
    </div>
    @if (signedIn() && user()?.roles?.includes('admin')) {
      <a hlmBtn variant="link" routerLink="/workspace">Workspace</a>
      <a hlmBtn variant="link" [routerLink]="'/activity/' + user()!.username">Activity</a>
    }
  </div>
  @if (signedIn() && user()?.roles?.includes('mentor_access')) {
    <app-ai-mentor class="hidden sm:inline-block" />
    <app-ai-mentor class="sm:hidden" iconOnly />
  }
  <app-request-feature class="hidden sm:inline-block" />
  <app-request-feature class="sm:hidden" iconOnly />
  <app-theme-switcher />
  @if (signedIn()) {
    <button [brnMenuTriggerFor]="usermenu" class="ml-2">
      <hlm-avatar>
        <img [src]="'https://github.com/' + user()!.username + '.png'" [alt]="user()?.name + '\'s avatar'" hlmAvatarImage />
        <span hlmAvatarFallback>
          {{ user()?.name?.slice(0, 2)?.toUpperCase() ?? '?' }}
        </span>
      </hlm-avatar>
    </button>
    <ng-template #usermenu>
      <hlm-menu>
        <hlm-menu-label>{{ user()!.name }}</hlm-menu-label>
        <hlm-menu-separator />
        <hlm-menu-group>
          <a hlmMenuItem [routerLink]="'/user/' + user()!.username" class="cursor-pointer">
            <hlm-icon name="lucideUser" hlmMenuIcon />
            <span>My Profile</span>
          </a>
          <a hlmMenuItem routerLink="/settings" class="cursor-pointer">
            <hlm-icon name="lucideSettings" hlmMenuIcon />
            <span>Settings</span>
          </a>
          <hlm-menu-separator />
          <button hlmMenuItem (click)="signOut()" class="cursor-pointer">
            <hlm-icon name="lucideLogOut" hlmMenuIcon />
            <span>Sign&nbsp;Out</span>
          </button>
        </hlm-menu-group>
      </hlm-menu>
    </ng-template>
  } @else if (loaded()) {
    <button hlmBtn (click)="signIn()">Sign&nbsp;In</button>
  }
</header>
