// webapp-react/src/components/practices/components/BadPracticeCard.tsx
import type { PullRequestBadPractice } from "@/api/types.gen";
import { stateConfig } from "../utils";
import { 
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useState } from "react";

interface BadPracticeCardProps {
  id: number;
  title: string;
  description: string;
  state: PullRequestBadPractice["state"];
  currUserIsDashboardUser?: boolean;
  onResolveBadPracticeAsFixed?: (id: number) => void;
}

export function BadPracticeCard({
  id,
  title,
  description,
  state,
  currUserIsDashboardUser = false,
  onResolveBadPracticeAsFixed,
}: BadPracticeCardProps) {
  const [dialogOpen, setDialogOpen] = useState(false);
  const stateInfo = stateConfig[state];
  const Icon = stateInfo.icon;

  const handleResolveAsFixed = () => {
    onResolveBadPracticeAsFixed?.(id);
  };

  const handleProvideFeedback = () => {
    setDialogOpen(false);
    // In the future, add implementation for feedback
  };

  return (
    <div className="flex flex-row justify-between items-center gap-2">
      <div className="flex flex-row justify-start items-center gap-4">
        <div>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger>
                <Icon className={`size-5 ${stateInfo.color}`} />
              </TooltipTrigger>
              <TooltipContent>
                <span>{stateInfo.text}</span>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <div className="flex flex-col">
          <h3 className="text-md font-semibold">{title}</h3>
          <p className="text-sm text-pretty">{description}</p>
        </div>
      </div>
      {currUserIsDashboardUser && (
        <div className="justify-self-end">
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline">Resolve</Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56">
                <DropdownMenuGroup>
                  <DropdownMenuItem onClick={handleResolveAsFixed}>
                    Resolve as fixed
                  </DropdownMenuItem>
                </DropdownMenuGroup>
                <DropdownMenuGroup>
                  <DropdownMenuItem>
                    Resolve as won't fix
                  </DropdownMenuItem>
                </DropdownMenuGroup>
                <DropdownMenuGroup>
                  <DropdownMenuItem onClick={() => setDialogOpen(true)}>
                    Resolve as wrong
                  </DropdownMenuItem>
                </DropdownMenuGroup>
                <DropdownMenuSeparator />
                <DropdownMenuGroup>
                  <DropdownMenuItem onClick={() => setDialogOpen(true)}>
                    Provide feedback
                  </DropdownMenuItem>
                </DropdownMenuGroup>
              </DropdownMenuContent>
            </DropdownMenu>

            <DialogContent>
              <DialogHeader>
                <DialogTitle>Provide feedback</DialogTitle>
                <DialogDescription>
                  Mark this bad practice with feedback that helps us improve the bad practice detection.
                </DialogDescription>
              </DialogHeader>
              <div className="py-4 grid gap-4">
                <div className="items-center grid grid-cols-4 gap-4">
                  {/* Feedback form controls would go here */}
                </div>
                <div className="items-start grid grid-cols-4 gap-4 h-40">
                  {/* Additional form controls would go here */}
                </div>
              </div>
              <DialogFooter>
                <Button type="submit" onClick={handleProvideFeedback}>
                  Submit feedback
                </Button>
              </DialogFooter>
              <div className="py-4 grid gap-4">
                <div className="items-center grid grid-cols-4 gap-4">
                  {/* Future form elements would go here */}
                </div>
                <div className="items-start grid grid-cols-4 gap-4 h-40">
                  {/* Future text area would go here */}
                </div>
              </div>
              <DialogFooter>
                <Button type="submit" onClick={handleProvideFeedback}>
                  Submit feedback
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      )}
    </div>
  );
}

// webapp/src/app/user/bad-practice-card/bad-practice-card.component.ts
import { Component, input } from '@angular/core';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';

@Component({
  selector: 'app-bad-practice-card',
  standalone: true,
  imports: [HlmCardModule],
  templateUrl: './bad-practice-card.component.html',
  styles: ``
})
export class BadPracticeCardComponent {
  title = input<string>();
  description = input<string>();
  repositoryName = input<string>();
  number = input<number>();
}

<div class="flex flex-row justify-between items-center gap-2">
  <div class="flex flex-row justify-start items-center gap-4">
    <div>
      <hlm-tooltip>
        <ng-icon hlmTooltipTrigger [name]="icon()" size="24" class="{{ color() }}"></ng-icon>
        <span *brnTooltipContent>{{ text() }}</span>
      </hlm-tooltip>
    </div>
    <div class="flex flex-col">
      <h3 class="text-md font-semibold">{{ title() }}</h3>
      <p class="text-sm text-pretty">{{ description() }}</p>
    </div>
  </div>
  @if (currUserIsDashboardUser()) {
    <div class="justify-self-end">
      <hlm-dialog>
        <button hlmBtn variant="outline" [brnMenuTriggerFor]="menu">Resolve</button>
        <ng-template #menu>
          <hlm-menu>
            <hlm-menu-group>
              <button hlmMenuItem (click)="resolveBadPracticeAsFixed(id())">Resolve as fixed</button>
            </hlm-menu-group>
            <hlm-menu-group>
              <button hlmMenuItem (click)="resolveBadPracticeAsWontFixed(id())">Resolve as won't fix</button>
            </hlm-menu-group>
            <hlm-menu-group>
              <button hlmMenuItem brnDialogTrigger (click)="resolveBadPracticeAsWrong(id())">Resolve as wrong</button>
            </hlm-menu-group>
            <hlm-menu-separator />
            <hlm-menu-group>
              <button hlmMenuItem brnDialogTrigger>Provide feedback</button>
            </hlm-menu-group>
          </hlm-menu>
        </ng-template>
        <hlm-dialog-content *brnDialogContent="let ctx">
          <hlm-dialog-header>
            <h3 hlmDialogTitle>Provide feedback</h3>
            <p hlmDialogDescription>Mark this bad practice with feedback that helps us improve the bad practice detection.</p>
          </hlm-dialog-header>
          <div class="py-4 grid gap-4">
            <div class="items-center grid grid-cols-4 gap-4">
              <label hlmLabel class="text-right">Feedback</label>
              <brn-select class="inline-block" placeholder="Select the type of feedback" [(ngModel)]="_selectedType">
                <hlm-select-trigger class="col-span-3">
                  <hlm-select-value />
                </hlm-select-trigger>
                <hlm-select-content>
                  @for (type of allFeedbackTypes(); track type) {
                    <hlm-option [value]="type">{{ type }}</hlm-option>
                  }
                </hlm-select-content>
              </brn-select>
            </div>
            <div class="items-start grid grid-cols-4 gap-4 h-40">
              <label hlmLabel for="explanation" class="text-right">Explanation</label>
              <textarea hlmInput id="explanation" class="col-span-3 h-full" [formControl]="_newExplanation"></textarea>
            </div>
          </div>
          <hlm-dialog-footer>
            <button hlmBtn brnDialogClose type="submit" (click)="this.provideFeedbackForBadPractice()">Submit feedback</button>
          </hlm-dialog-footer>
        </hlm-dialog-content>
      </hlm-dialog>
    </div>
  }
</div>
