// webapp-react/src/components/chat/ChatInput.tsx
import React, { useState } from 'react';
import { Send, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { Spinner } from '@/components/ui/spinner';

interface ChatInputProps {
  isClosed: boolean;
  isSending: boolean;
  onSendMessage: (message: string) => void;
}

export function ChatInput({ isClosed, isSending, onSendMessage }: ChatInputProps) {
  const [message, setMessage] = useState<string>('');

  const handleSendMessage = () => {
    if (isSending || !message.trim()) {
      return;
    }

    onSendMessage(message);
    setMessage('');
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="flex items-start space-x-3">
      {isClosed ? (
        <Alert className="flex flex-row space-x-3">
          <AlertCircle className="h-4 w-4" />
          <div>
            <AlertTitle>This session is closed.</AlertTitle>
            <AlertDescription>
              Please, start a new session or continue messaging in your most recent one.
            </AlertDescription>
          </div>
        </Alert>
      ) : (
        <Textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Message AI Mentor"
          className="w-full min-h-20"
          style={{ resize: "none" }}
          disabled={isSending || isClosed}
        />
      )}
      <Button 
        disabled={isSending || isClosed}
        onClick={handleSendMessage}
        size="icon"
        aria-label="Send Message"
      >
        {isSending ? (
          <Spinner size="sm" />
        ) : (
          <Send className="h-5 w-5" />
        )}
      </Button>
    </div>
  );
}

// webapp/src/app/mentor/chat-input/chat-input.component.ts
import { Component, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LucideAngularModule, Send, CircleAlert } from 'lucide-angular';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { HlmSpinnerComponent } from '@spartan-ng/ui-spinner-helm';
import { HlmInputDirective } from '@spartan-ng/ui-input-helm';
import { HlmAlertDescriptionDirective, HlmAlertDirective, HlmAlertTitleDirective } from '@spartan-ng/ui-alert-helm';

@Component({
  selector: 'app-chat-input',
  templateUrl: './chat-input.component.html',
  standalone: true,
  imports: [
    CommonModule,
    HlmButtonModule,
    HlmAlertDescriptionDirective,
    HlmAlertDirective,
    HlmAlertTitleDirective,
    HlmSpinnerComponent,
    FormsModule,
    HlmCardModule,
    HlmInputDirective,
    LucideAngularModule
  ]
})
export class ChatInputComponent {
  protected Send = Send;
  protected Alert = CircleAlert;

  isClosed = input.required<boolean>();
  isSending = input.required<boolean>();
  message = signal<string>('');
  sendMessage = output<string>();

  onSendMessage() {
    if (this.isSending() || !this.message()) {
      return;
    }

    this.sendMessage.emit(this.message());
    setTimeout(() => {
      this.message.set('');
    });
  }
}

<div class="flex items-start space-x-3">
  @if (isClosed()) {
    <div hlmAlert class="flex flex-row space-x-3">
      <lucide-angular [img]="Alert" class="size-4" />
      <div>
        <h4 hlmAlertTitle>Please continue messaging in your most recent session.</h4>
        <p hlmAlertDesc>To stay organized, starting a new session automatically closes the previous one. <br /></p>
      </div>
    </div>
  } @else {
    <textarea
      hlmInput
      [(ngModel)]="message"
      placeholder="Message AI Mentor"
      style="resize: none"
      (keydown.enter)="onSendMessage()"
      class="w-full min-h-20"
      [disabled]="isSending() || isClosed()"
    ></textarea>
  }
  <button hlmBtn [disabled]="isSending() || isClosed()" aria-describedby="Send Message" (click)="onSendMessage()" variant="default" size="icon">
    @if (isSending()) {
      <hlm-spinner size="sm" />
    } @else {
      <lucide-angular [img]="Send" class="size-5" />
    }
  </button>
</div>
