// webapp/src/app/ui/input/input.component.ts
import { Component, computed, input, output } from '@angular/core';
import type { ClassValue } from 'clsx';
import { VariantProps } from 'class-variance-authority';
import { cn } from 'app/utils';
import { cva } from 'app/storybook.helper';

const [inputVariants, args, argTypes] = cva(
  'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
  {
    variants: {
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 px-2 py-1',
        lg: 'h-11 px-4 py-3'
      }
    },
    defaultVariants: {
      size: 'default'
    }
  }
);

export { args, argTypes };

interface InputVariants extends VariantProps<typeof inputVariants> {}

@Component({
  selector: 'app-input',
  standalone: true,
  templateUrl: './input.component.html'
})
export class AppInputComponent {
  class = input<ClassValue>('');
  type = input<string>('text');
  placeholder = input<string>('');
  size = input<InputVariants['size']>('default');
  disabled = input<boolean>(false);
  value = input<string>('');
  id = input<string>('');

  valueChange = output<string>();

  onInput(event: Event) {
    const inputValue = (event.target as HTMLInputElement).value;
    this.valueChange.emit(inputValue);
  }

  computedClass = computed(() => cn(inputVariants({ size: this.size() }), this.class()));
}

<input
  [class]="computedClass()"
  [type]="type()"
  [placeholder]="placeholder()"
  [disabled]="disabled()"
  [value]="value()"
  [id]="id()"
  (input)="onInput($event)"
>

// webapp/src/components/ui/input.tsx
import type * as React from "react";
import { Input as InputPrimitive } from "@base-ui/react/input";

import { cn } from "@/lib/utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
	return (
		<InputPrimitive
			type={type}
			data-slot="input"
			className={cn(
				"dark:bg-input/30 border-input focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 disabled:bg-input/50 dark:disabled:bg-input/80 h-8 rounded-lg border bg-transparent px-2.5 py-1 text-base transition-colors file:h-6 file:text-sm file:font-medium focus-visible:ring-[3px] aria-invalid:ring-[3px] md:text-sm file:text-foreground placeholder:text-muted-foreground w-full min-w-0 outline-none file:inline-flex file:border-0 file:bg-transparent disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50",
				className,
			)}
			{...props}
		/>
	);
}

export { Input };
