// webapp/src/app/components/theme-switcher/theme-switcher.component.ts
import { Component, inject } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import { ButtonComponent } from 'app/ui/button/button.component';
import { AppTheme, ThemeSwitcherService } from './theme-switcher.service';
import { animate, state, style, transition, trigger } from '@angular/animations';

@Component({
  selector: 'app-theme-switcher',
  standalone: true,
  imports: [ButtonComponent, LucideAngularModule],
  templateUrl: './theme-switcher.component.html',
  animations: [
    trigger('iconTrigger', [
      state('*', style({ transform: 'rotate(0deg)' })),
      transition('light => dark', animate('0.25s ease-out', style({ transform: 'rotate(90deg)' }))),
      transition('dark => light', animate('0.25s ease-out', style({ transform: 'rotate(360deg)' })))
    ])
  ]
})
export class ThemeSwitcherComponent {
  themeSwitcherService = inject(ThemeSwitcherService);

  toggleTheme() {
    if (this.themeSwitcherService.currentTheme() === AppTheme.DARK) {
      this.themeSwitcherService.setLightTheme();
    } else {
      this.themeSwitcherService.setDarkTheme();
    }
  }
}

<app-button (click)="toggleTheme()" variant="outline" size="icon">
  <div [@iconTrigger]="this.themeSwitcherService.currentTheme() ?? 'dark'">
    <lucide-angular [name]="this.themeSwitcherService.currentTheme() === 'dark' ? 'sun' : 'moon'" class="size-5" />
  </div>
</app-button>

// keycloakify/src/components/theme-switcher.tsx
import React from "react";
import { useTheme, AppTheme } from "./theme-context";
import { Sun, Moon } from "lucide-react";
import { Button } from "./ui/button";

const ThemeSwitcher: React.FC = () => {
    const { currentTheme, setLightTheme, setDarkTheme } = useTheme();

    const toggleTheme = () => {
        if (currentTheme === AppTheme.DARK) {
            setLightTheme();
        } else if (currentTheme === AppTheme.LIGHT) {
            setDarkTheme();
        } else {
            // If 'auto', decide based on system preference or default to dark
            const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
            if (prefersDark) {
                setLightTheme();
            } else {
                setDarkTheme();
            }
        }
    };

    const getIcon = () => {
        if (currentTheme === AppTheme.DARK) {
            return <Moon className="icon" />;
        } else if (currentTheme === AppTheme.LIGHT) {
            return <Sun className="icon" />;
        } else {
            // 'auto' - determine system preference
            const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
            return prefersDark ? <Moon className="icon" /> : <Sun className="icon" />;
        }
    };

    return (
        <Button variant="outline" size="icon" onClick={toggleTheme} aria-label="Toggle Theme">
            {getIcon()}
        </Button>
    );
};

export default ThemeSwitcher;
