// webapp/src/app/core/header/header.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideAngularModule, Hammer } from 'lucide-angular';
import { HlmButtonModule } from '@spartan-ng/ui-button-helm';
import { SecurityStore } from '@app/core/security/security-store.service';
import { ThemeSwitcherComponent } from '@app/core/theme/theme-switcher.component';
import { RequestFeatureComponent } from './request-feature/request-feature.component';
import { environment } from 'environments/environment';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  standalone: true,
  imports: [RouterLink, LucideAngularModule, ThemeSwitcherComponent, HlmButtonModule, RequestFeatureComponent]
})
export class HeaderComponent {
  protected Hammer = Hammer;

  securityStore = inject(SecurityStore);
  signedIn = this.securityStore.signedIn;

  protected signOut() {
    this.securityStore.signOut();
  }

  protected signIn() {
    if (environment.keycloak.skipLoginPage) {
      const authUrl =
        `${environment.keycloak.url}/realms/${environment.keycloak.realm}/protocol/openid-connect/auth` +
        `?client_id=${encodeURIComponent(environment.keycloak.clientId)}` +
        `&redirect_uri=${encodeURIComponent(environment.clientUrl)}` +
        `&response_type=code` +
        `&scope=openid` +
        `&kc_idp_hint=${encodeURIComponent('github')}`;

      // Redirect the user to the Keycloak GitHub login
      window.location.href = authUrl;
    } else {
      this.securityStore.signIn();
    }
  }
}

<header class="container flex items-center justify-between pt-4 gap-2">
  <div class="flex gap-4 items-center flex-1">
    <div class="flex items-center gap-2">
      <a class="flex gap-2 items-center hover:text-muted-foreground" routerLink="/">
        <lucide-angular [img]="Hammer" class="size-8 sm:size-6" />
        <span class="hidden sm:inline-block text-xl font-semibold">Hephaestus</span>
      </a>
      <span class="text-xs font-semibold mt-1 text-muted-foreground">{{ version }}</span>
    </div>
    @if (signedIn() && user()?.roles?.includes('admin')) {
      <a hlmBtn variant="link" routerLink="/workspace">Workspace</a>
      <a hlmBtn variant="link" [routerLink]="'/activity/' + user()!.username">Activity</a>
    }
  </div>
  @if (signedIn() && user()?.roles?.includes('mentor_access')) {
    <app-ai-mentor class="hidden sm:inline-block" />
    <app-ai-mentor class="sm:hidden" iconOnly />
  }
  <app-request-feature class="hidden sm:inline-block" />
  <app-request-feature class="sm:hidden" iconOnly />
  <app-theme-switcher />
  @if (signedIn()) {
    <button [brnMenuTriggerFor]="usermenu" class="ml-2">
      <hlm-avatar>
        <img [src]="'https://github.com/' + user()!.username + '.png'" [alt]="user()?.name + '\'s avatar'" hlmAvatarImage />
        <span hlmAvatarFallback>
          {{ user()?.name?.slice(0, 2)?.toUpperCase() ?? '?' }}
        </span>
      </hlm-avatar>
    </button>
    <ng-template #usermenu>
      <hlm-menu>
        <hlm-menu-label>{{ user()!.name }}</hlm-menu-label>
        <hlm-menu-separator />
        <hlm-menu-group>
          <a hlmMenuItem [routerLink]="'/user/' + user()!.username" class="cursor-pointer">
            <hlm-icon name="lucideUser" hlmMenuIcon />
            <span>My Profile</span>
          </a>
          <a hlmMenuItem routerLink="/settings" class="cursor-pointer">
            <hlm-icon name="lucideSettings" hlmMenuIcon />
            <span>Settings</span>
          </a>
          <hlm-menu-separator />
          <button hlmMenuItem (click)="signOut()" class="cursor-pointer">
            <hlm-icon name="lucideLogOut" hlmMenuIcon />
            <span>Sign&nbsp;Out</span>
          </button>
        </hlm-menu-group>
      </hlm-menu>
    </ng-template>
  } @else if (loaded()) {
    <button hlmBtn (click)="signIn()">Sign&nbsp;In</button>
  }
</header>

// webapp-react/src/components/header/Header.tsx
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Hammer, User, LogOut, Settings, MessageSquarePlus } from "lucide-react";
import { useAuth } from "@/lib/auth/AuthContext";
import environment from "@/environment";
import { 
  Avatar, 
  AvatarFallback, 
  AvatarImage 
} from "@/components/ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { ModeToggle } from "@/components/mode-toggle/ModeToggle";

export default function Header() {
  const { isAuthenticated, isLoading, username, login, logout, hasRole } = useAuth();

  const showAdmin = isAuthenticated && hasRole('admin');
  const showMentor = isAuthenticated && hasRole('mentor_access');

  return (
    <header className="container flex items-center justify-between pt-4 gap-2">
      <div className="flex gap-4 items-center flex-1">
        <div className="flex items-center gap-2">
          <Link to="/" className="flex gap-2 items-center hover:text-muted-foreground">
            <Hammer className="text-2xl sm:text-3xl" />
            <span className="hidden sm:inline-block text-xl font-semibold">Hephaestus</span>
          </Link>
          <span className="text-xs font-semibold mt-1 text-muted-foreground">{environment.version}</span>
        </div>
        
        {showAdmin && (
          <div className="hidden md:flex gap-2">
            <Button asChild variant="link">
              <Link to="/workspace">Workspace</Link>
            </Button>
            <Button asChild variant="link">
              <Link to="/user/$username/activity" params={{ username: username ?? '' }}>Activity</Link>
            </Button>
            <Button asChild variant="link">
              <Link to="/teams">Teams</Link>
            </Button>
          </div>
        )}
      </div>
      
      {showMentor && (
        <>
          <Button variant="ghost" size="icon" className="hidden sm:inline-flex">
            <MessageSquarePlus className="h-5 w-5" />
            <span className="ml-2">AI Mentor</span>
          </Button>
          <Button variant="ghost" size="icon" className="sm:hidden">
            <MessageSquarePlus className="h-5 w-5" />
          </Button>
        </>
      )}
      
      <Button variant="ghost" size="icon" className="hidden sm:inline-flex">
        <MessageSquarePlus className="h-5 w-5" />
        <span className="ml-2">Request Feature</span>
      </Button>
      
      <Button variant="ghost" size="icon" className="sm:hidden">
        <MessageSquarePlus className="h-5 w-5" />
      </Button>
      
      <ModeToggle />
      
      <div className="flex items-center gap-2">
        {!isAuthenticated ? (
          <Button onClick={() => login()} disabled={isLoading}>
            {isLoading ? "Loading..." : "Sign In"}
          </Button>
        ) : (
          <div className="flex items-center gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="relative h-8 w-8 rounded-full">
                  <Avatar>
                    <AvatarImage src={`https://github.com/${username}.png`} alt={`${username}'s avatar`} />
                    <AvatarFallback>{username?.slice(0, 2)?.toUpperCase() || '?'}</AvatarFallback>
                  </Avatar>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56" align="end" forceMount>
                <DropdownMenuLabel className="font-normal">
                  <div className="flex flex-col space-y-1">
                    <p className="text-sm font-medium leading-none">{username}</p>
                  </div>
                </DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuGroup>
                  <DropdownMenuItem asChild>
                    <Link to="/user/$username" params={{ username: username ?? '' }}> 
                      <User className="mr-2 h-4 w-4" />
                      <span>My Profile</span>
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem asChild>
                    <Link to="/settings">
                      <Settings className="mr-2 h-4 w-4" />
                      <span>Settings</span>
                    </Link>
                  </DropdownMenuItem>
                </DropdownMenuGroup>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={() => logout()}>
                  <LogOut className="mr-2 h-4 w-4" />
                  <span>Sign Out</span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        )}
      </div>
    </header>
  );
}
