// webapp-react/src/components/practices/components/PullRequestBadPracticeCard.tsx
import React, { useState } from "react";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { BadPracticeCard } from "./BadPracticeCard";
import type { PullRequestBadPractice, LabelInfo } from "@/api/types.gen";
import { formatTitle } from "../utils";
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible";
import { 
  RefreshCw, 
  GitPullRequest, 
  GitPullRequestDraft, 
  GitPullRequestClosed, 
  GitMerge,
  FoldVertical
} from "lucide-react";
import { GitHubLabel } from "./GitHubLabel";

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { format, parseISO } from "date-fns";

interface PullRequestBadPracticeCardProps {
  id: number;
  title?: string;
  number?: number;
  additions?: number;
  deletions?: number;
  htmlUrl?: string;
  repositoryName?: string;
  createdAt?: string;
  updatedAt?: string;
  state?: string;
  isDraft?: boolean;
  isMerged?: boolean;
  pullRequestLabels?: Array<LabelInfo>;
  badPractices?: Array<PullRequestBadPractice>;
  oldBadPractices?: Array<PullRequestBadPractice>;
  badPracticeSummary?: string;
  isLoading?: boolean;
  openCard?: boolean;
  currUserIsDashboardUser?: boolean;
  onDetectBadPractices?: (id: number) => void;
}

export function PullRequestBadPracticeCard({
  id,
  title = "",
  number = 0,
  additions = 0,
  deletions = 0,
  htmlUrl = "",
  repositoryName = "",
  createdAt = "",
  updatedAt = "",
  state = "OPEN",
  isDraft = false,
  isMerged = false,
  pullRequestLabels = [],
  badPractices = [],
  oldBadPractices = [],
  badPracticeSummary = "",
  isLoading = false,
  openCard = false,
  currUserIsDashboardUser = false,
  onDetectBadPractices,
}: PullRequestBadPracticeCardProps) {
  const [isOpen, setIsOpen] = useState(openCard);
  
  const displayCreated = createdAt ? format(parseISO(createdAt), 'MMM d') : null;
  const displayUpdated = updatedAt ? format(parseISO(updatedAt), 'MMM d, HH:mm') : null;
  const formattedTitle = formatTitle(title);
  const expandEnabled = badPractices.length > 0;
  
  // Get the appropriate icon and color based on PR state
  const getIssueIconAndColor = () => {
    if (isDraft) {
      return { icon: GitPullRequestDraft, color: "text-github-muted-foreground" };
    } else if (isMerged) {
      return { icon: GitMerge, color: "text-purple-500" };
    } else if (state === "CLOSED") {
      return { icon: GitPullRequestClosed, color: "text-github-danger-foreground" };
    } else {
      return { icon: GitPullRequest, color: "text-github-success-foreground" };
    }
  };
  
  // Sort practices by severity
  const orderedBadPractices = [...badPractices].sort((a, b) => {
    const severityOrder = {
      CRITICAL_ISSUE: 0,
      NORMAL_ISSUE: 1,
      MINOR_ISSUE: 2,
      GOOD_PRACTICE: 3,
      FIXED: 4,
      WONT_FIX: 5,
      WRONG: 6
    };
    return severityOrder[a.state as keyof typeof severityOrder] - severityOrder[b.state as keyof typeof severityOrder];
  });

  const orderedOldBadPractices = [...oldBadPractices || []].sort((a, b) => {
    const severityOrder = {
      CRITICAL_ISSUE: 0,
      NORMAL_ISSUE: 1,
      MINOR_ISSUE: 2,
      GOOD_PRACTICE: 3,
      FIXED: 4,
      WONT_FIX: 5,
      WRONG: 6
    };
    return severityOrder[a.state as keyof typeof severityOrder] - severityOrder[b.state as keyof typeof severityOrder];
  });

  const handleDetectClick = () => {
    if (onDetectBadPractices) {
      onDetectBadPractices(id);
    }
  };

  const detectedString = badPractices.length > 0
    ? `${badPractices.length} practice${badPractices.length !== 1 ? "s" : ""} detected`
    : "No practices detected";

  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <Card>
        <div className="flex flex-col gap-1 pt-2 pl-6 pr-2">
          <div className="flex justify-between items-center text-sm text-github-muted-foreground h-10">
            <span>
              {isLoading ? (
                <>
                  <Skeleton className="size-5 bg-green-500/30" />
                  <Skeleton className="h-4 w-16 lg:w-36" />
                </>
              ) : (
                <span className="font-medium flex justify-center items-center space-x-1">
                  {React.createElement(getIssueIconAndColor().icon, { 
                    className: `mr-1 size-[18px] ${getIssueIconAndColor().color}` 
                  })}
                  <a href={htmlUrl} className="hover:underline">
                    {repositoryName} #{number}
                  </a>
                  <span>
                    on {displayCreated}. Updated on {displayUpdated}
                  </span>
                </span>
              )}
            </span>
            <span className="font-medium flex justify-center items-center gap-2">
              {isLoading ? (
                <>
                  <Skeleton className="h-4 w-16 lg:w-36" />
                  <Skeleton className="size-5" />
                </>
              ) : (
                <>
                  <span className="pr-2">{detectedString}</span>
                  {currUserIsDashboardUser && (
                    <Button 
                      variant="outline"
                      size="sm"
                      className="gap-1"
                      onClick={handleDetectClick}
                    >
                      {/* This would ideally use a loading state like in Angular */}
                      <RefreshCw className="size-4" />
                      <span>Detect</span>
                    </Button>
                  )}
                  {expandEnabled && (
                    <CollapsibleTrigger asChild>
                      <Button variant="ghost" size="icon">
                        <FoldVertical className="size-[18px] text-github-muted-foreground" />
                      </Button>
                    </CollapsibleTrigger>
                  )}
                </>
              )}
            </span>
          </div>
          <div className="flex justify-between font-medium contain-inline-size gap-2">
            <span>
              {isLoading ? (
                <Skeleton className="h-6 w-3/4" />
              ) : (
                <a
                  href={htmlUrl}
                  rel="noopener noreferrer"
                  className="hover:underline"
                  dangerouslySetInnerHTML={{ __html: formattedTitle }}
                />
              )}
            </span>
            <span className="flex items-center space-x-2 pr-4">
              {isLoading ? (
                <>
                  <Skeleton className="h-4 w-8 bg-green-500/30" />
                  <Skeleton className="h-4 w-8 bg-destructive/20" />
                </>
              ) : (
                <>
                  <span className="text-github-success-foreground font-bold">+{additions}</span>
                  <span className="text-github-danger-foreground font-bold">-{deletions}</span>
                </>
              )}
            </span>
          </div>
          {!isLoading && pullRequestLabels && pullRequestLabels.length > 0 && (
            <div className="flex flex-wrap pb-1 gap-2 space-x-0">
              {pullRequestLabels.map(label => (
                <GitHubLabel key={label.id} label={label} />
              ))}
            </div>
          )}
        </div>
        {!isLoading && (
          <div className="gap-2 space-x-0 text-left px-6 pb-2">
            <CollapsibleContent>
              <Separator />
              {badPracticeSummary && (
                <p className="text-sm text-pretty">{badPracticeSummary}</p>
              )}
              
              {orderedBadPractices.map((badpractice) => (
                <React.Fragment key={badpractice.id}>
                  <Separator />
                  <BadPracticeCard
                    id={badpractice.id}
                    title={badpractice.title}
                    description={badpractice.description}
                    state={badpractice.state}
                    currUserIsDashboardUser={currUserIsDashboardUser}
                  />
                </React.Fragment>
              ))}
              
              {orderedOldBadPractices.length > 0 && (
                <>
                  <Separator />
                  <Accordion type="single" collapsible className="w-full">
                    <AccordionItem value="old-practices" className="border-none">
                      <AccordionTrigger>
                        Old good and bad practices
                      </AccordionTrigger>
                      <AccordionContent>
                        {orderedOldBadPractices.map(badpractice => (
                          <React.Fragment key={`old-${badpractice.id}`}>
                            <Separator />
                            <BadPracticeCard
                              id={badpractice.id}
                              title={badpractice.title}
                              description={badpractice.description}
                              state={badpractice.state}
                              currUserIsDashboardUser={currUserIsDashboardUser}
                            />
                          </React.Fragment>
                        ))}
                      </AccordionContent>
                    </AccordionItem>
                  </Accordion>
                </>
              )}
            </CollapsibleContent>
          </div>
        )}
      </Card>
    </Collapsible>
  );
}

// webapp/src/app/user/pull-request-bad-practice-card/pull-request-bad-practice-card.component.ts
import { Component, computed, input } from '@angular/core';
import { PullRequestInfo, LabelInfo, PullRequestBadPractice } from '@app/core/modules/openapi';
import { NgIcon } from '@ng-icons/core';
import { octCheck, octComment, octFileDiff, octGitPullRequest, octGitPullRequestClosed, octGitPullRequestDraft, octGitMerge, octX, octFold } from '@ng-icons/octicons';
import { HlmCardModule } from '@spartan-ng/ui-card-helm';
import { HlmSkeletonComponent } from '@spartan-ng/ui-skeleton-helm';

import dayjs from 'dayjs/esm';
import { BadPracticeCardComponent } from '@app/user/bad-practice-card/bad-practice-card.component';
import { BrnSeparatorComponent } from '@spartan-ng/ui-separator-brain';
import { HlmSeparatorDirective } from '@spartan-ng/ui-separator-helm';
import { BrnCollapsibleComponent, BrnCollapsibleContentComponent, BrnCollapsibleTriggerDirective } from '@spartan-ng/ui-collapsible-brain';
import { HlmButtonDirective } from '@spartan-ng/ui-button-helm';
import { GithubLabelComponent } from '@app/ui/github-label/github-label.component';
import { cn } from '@app/utils';
import { formatTitle } from '@app/utils';

@Component({
  selector: 'app-pull-request-bad-practice-card',
  templateUrl: './pull-request-bad-practice-card.component.html',
  imports: [
    NgIcon,
    HlmCardModule,
    HlmSkeletonComponent,
    BadPracticeCardComponent,
    BrnSeparatorComponent,
    HlmSeparatorDirective,
    BrnCollapsibleComponent,
    BrnCollapsibleContentComponent,
    BrnCollapsibleTriggerDirective,
    HlmButtonDirective,
    GithubLabelComponent
  ]
})
export class PullRequestBadPracticeCardComponent {
  protected readonly octCheck = octCheck;
  protected readonly octX = octX;
  protected readonly octComment = octComment;
  protected readonly octFileDiff = octFileDiff;
  protected readonly octFold = octFold;

  isLoading = input(false);
  class = input('');
  title = input<string>();
  number = input<number>();
  additions = input<number>();
  deletions = input<number>();
  htmlUrl = input<string>();
  repositoryName = input<string>();
  createdAt = input<string>();
  state = input<PullRequestInfo.StateEnum>();
  isDraft = input<boolean>();
  isMerged = input<boolean>();
  pullRequestLabels = input<Array<LabelInfo>>();
  badPractices = input<Array<PullRequestBadPractice>>();

  displayCreated = computed(() => dayjs(this.createdAt()));
  displayTitle = computed(() => formatTitle(this.title() ?? ''));
  computedClass = computed(() => cn('w-full', !this.isLoading() ? 'hover:bg-accent/50 cursor-pointer' : '', this.class()));

  issueIconAndColor = computed(() => {
    var icon: string;
    var color: string;

    if (this.state() === PullRequestInfo.StateEnum.Open) {
      if (this.isDraft()) {
        icon = octGitPullRequestDraft;
        color = 'text-github-muted-foreground';
      } else {
        icon = octGitPullRequest;
        color = 'text-github-open-foreground';
      }
    } else {
      if (this.isMerged()) {
        icon = octGitMerge;
        color = 'text-github-done-foreground';
      } else {
        icon = octGitPullRequestClosed;
        color = 'text-github-closed-foreground';
      }
    }

    return { icon, color };
  });
}

<brn-collapsible>
  <section hlmCard>
    <div class="flex flex-col gap-1 pt-2 pl-6 pr-2">
      <div class="flex justify-between items-center text-sm text-github-muted-foreground h-10">
        <span>
          @if (isLoading()) {
            <hlm-skeleton class="size-5 bg-green-500/30"></hlm-skeleton>
            <hlm-skeleton class="h-4 w-16 lg:w-36"></hlm-skeleton>
          } @else {
            <span class="font-medium flex justify-center items-center space-x-1">
              <ng-icon [name]="issueIconAndColor().icon" size="18" [class]="'mr-1 ' + issueIconAndColor().color"></ng-icon>
              <a [href]="htmlUrl()">{{ repositoryName() }} #{{ number() }} </a>
              <span> on {{ displayCreated().format('MMM D') }}. Updated on {{ displayUpdated().format('MMM D, HH:mm') }} </span>
            </span>
          }
        </span>
        <span class="font-medium flex justify-center items-center gap-2">
          @if (isLoading()) {
            <hlm-skeleton class="h-4 w-16 lg:w-36"></hlm-skeleton>
            <hlm-skeleton class="size-5"></hlm-skeleton>
          } @else {
            <span class="pr-2"> {{ detectedString() }} </span>
            @if (currUserIsDashboardUser()) {
              <button hlmBtn variant="outline" size="sm" class="gap-1" (click)="this.detectBadPracticesForPr(id())">
                @if (this.detectBadPracticesForPrMutation.isPending()) {
                  <hlm-spinner class="size-4" />
                } @else {
                  <ng-icon name="octSync" class="size-8" />
                }
                <span>Detect</span>
              </button>
            }
            @if (expandEnabled()) {
              <button brnCollapsibleTrigger hlmBtn variant="ghost">
                <ng-icon name="octFold" size="18" class="text-github-muted-foreground"></ng-icon>
              </button>
            }
          }
        </span>
      </div>
      <div class="flex justify-between font-medium contain-inline-size gap-2">
        <span>
          @if (isLoading()) {
            <hlm-skeleton class="h-6 w-3/4"></hlm-skeleton>
          } @else {
            <a [href]="htmlUrl()" [innerHTML]="displayTitle()" class=""></a>
          }
        </span>
        <span class="flex items-center space-x-2 pr-4">
          @if (isLoading()) {
            <hlm-skeleton class="h-4 w-8 bg-green-500/30"></hlm-skeleton>
            <hlm-skeleton class="h-4 w-8 bg-destructive/20"></hlm-skeleton>
          } @else {
            <span class="text-github-success-foreground font-bold">+{{ additions() }}</span>
            <span class="text-github-danger-foreground font-bold">-{{ deletions() }}</span>
          }
        </span>
      </div>
      @if (!isLoading()) {
        <div class="flex flex-wrap pb-1 gap-2 space-x-0">
          @for (label of pullRequestLabels(); track label.name) {
            <app-github-label [label]="label"></app-github-label>
          }
        </div>
      }
    </div>
    @if (!isLoading()) {
      <div class="gap-2 space-x-0 text-left px-6 pb-2">
        <brn-collapsible-content>
          <brn-separator hlmSeparator />
          <p class="text-sm text-pretty">{{ badPracticeSummary() }}</p>
          @for (badpractice of orderedBadPractices(); track badpractice.title) {
            <brn-separator hlmSeparator />
            <app-bad-practice-card
              [id]="badpractice.id"
              [title]="badpractice.title"
              [description]="badpractice.description"
              [state]="badpractice.state"
              [currUserIsDashboardUser]="currUserIsDashboardUser()"
            ></app-bad-practice-card>
          }
          @if (orderedOldBadPractices().length > 0) {
            <brn-separator hlmSeparator />
            <div hlmAccordion>
              <div hlmAccordionItem>
                <button hlmAccordionTrigger>
                  Old good and bad practices
                  <ng-icon name="lucideChevronDown" hlm hlmAccIcon />
                </button>
                <hlm-accordion-content>
                  @for (badpractice of orderedOldBadPractices(); track badpractice.title) {
                    <brn-separator hlmSeparator />
                    <app-bad-practice-card
                      [id]="badpractice.id"
                      [title]="badpractice.title"
                      [description]="badpractice.description"
                      [state]="badpractice.state"
                      [currUserIsDashboardUser]="currUserIsDashboardUser()"
                    ></app-bad-practice-card>
                  }
                </hlm-accordion-content>
              </div>
            </div>
          }
        </brn-collapsible-content>
      </div>
    }
  </section>
</brn-collapsible>
